### ISSUE TITLE
Can I manually add resources to the add-on?

### ISSUE THREAD

**Issue by MacgyverJohnson** [Synzvato/decentraleyes#100]
Hello there dev,
Is is possible to add a custom cdn? I visited a site which is in top 1000 sites (mangafox.me) globally but if i enable "Block request for missing request" then the sites search function(not the advanced search option but the search as u type one) does not work...turning off that option and reloading the page makes the search function working again.....so is it possible to add this cdn.....can i add it manually...if so then how? the cdn is "mfcdn.net"

**Comment by Synzvato** [comment]
Hi @MacgyverJohnson, thanks for sharing your concerns!

Decentraleyes will never break traffic that goes to unsupported CDNs. Mangafox's own CDN ```mfcdn.net``` is likely to be maintained by the same people that maintain the website, so that's all good.

The problem here is that apart from relying on their self-hosted CDN, they also depend on Google Hosted Libraries ```googleapis.com```. This is what's causing the issues. To ensure ease of use and stability, the preference you enabled _(for blocking requests for missing resources)_ is disabled by default.

There's no direct support for adding custom libraries and mappings. For now, this is out of scope, but that could very well change in the future. If you know how to install and run unsigned add-ons inside of your browser, you could manually add the missing resource to the add-on:

1. Download ```v1.3.5``` of the add-on _(right click the download button, save the target)_.
2. Open the downloaded ```.xpi``` archive using your favorite archive manager.
3. Add ```'resources/jqueryui/1.8.16/jquery-ui.min.js.dec': true,``` to ```/lib/files.js```.
4. Create a new folder called ```1.8.16``` inside of ```/data/resources/jqueryui```.
5. Download the [missing file](https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js), add it to the new folder, and name it ```jquery-ui.min.js.dec```.
6. Install and start using your custom, unsigned, copy inside of your web browser.

I hope this helps! If not, feel free to let me know.

**Comment by Gitoffthelawn** [comment]
That info is so good it is worthy of being included in an advanced FAQ.

**Comment by MacgyverJohnson** [comment]
Thanks @Synzvato for the treasure trove of ur wisdom .....facing issues firefox saying addon cannot be installed because addon is corrupt....addon compatibility is turned off...followed all the steps..pls help...added 'resources/jqueryui/1.8.16/jquery-ui.min.js.dec': true, like this
`// jQuery UI
    'resources/jqueryui/1.5.3/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.6.0/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.7.3/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.8.16/jquery-ui.min.js.dec': true,
	'resources/jqueryui/1.8.24/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.9.2/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.10.4/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.11.0/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.11.1/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.11.2/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.11.3/jquery-ui.min.js.dec': true,
    'resources/jqueryui/1.11.4/jquery-ui.min.js.dec': true,`
placed missing file in correctly created data\resources\jqueryui\1.8.16
is this the case of file (manifest)integrity change(md5/sha256) ..if so how to overcome this
I have used unsigned addons since forever...i did uninstall and restarted firefox before doing this( i know decentraleyes is restartless but to be on the safe side)......would u kindly have a look at it?(i like to to do this myself for future purposes so would greatly appreciate if  would consider to show the way)

Strange...i added from about:debugging>load temporaryaddon>folder>select install.rdf and it works now??? Mangafox search is working like the wind =)

On another note how to detect the missing file and its download link?

Thanks once again.....

**Comment by Feodor2** [comment]
> On another note how to detect the missing file and its download link?

You can try fiddler but if the site is https it most likely not help. Searching solution for https for myself
http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureBrowsers

**Comment by Feodor2** [comment]
To make fiddler work with firefox do in fiddler Tools Fiddler options HTTPS Actions Export root certificate to desktop, then do import that certificate to firefox.

**Comment by BananaMangoFestival** [comment]
> 

Hi @MacgyverJohnson, thanks for sharing your concerns!

Decentraleyes will never break traffic that goes to unsupported CDNs. Mangafox's own CDN mfcdn.net is likely to be maintained by the same people that maintain the website, so that's all good.

The problem here is that apart from relying on their self-hosted CDN, they also depend on Google Hosted Libraries googleapis.com. This is what's causing the issues. To ensure ease of use and stability, the preference you enabled (for blocking requests for missing resources) is disabled by default.

There's no direct support for adding custom libraries and mappings. For now, this is out of scope, but that could very well change in the future. If you know how to install and run unsigned add-ons inside of your browser, you could manually add the missing resource to the add-on:

    Download v1.3.5 of the add-on (right click the download button, save the target).
    Open the downloaded .xpi archive using your favorite archive manager.
    Add 'resources/jqueryui/1.8.16/jquery-ui.min.js.dec': true, to /lib/files.js.
    Create a new folder called 1.8.16 inside of /data/resources/jqueryui.
    Download the missing file, add it to the new folder, and name it jquery-ui.min.js.dec.
    Install and start using your custom, unsigned, copy inside of your web browser.

I hope this helps! If not, feel free to let me know.

> This no longer works since 1.3.6 for my part, I made the same handling and the targeted website is [T411](https://www.t411.ch/), It considers that I block the resource.

**Comment by Synzvato** [comment]
@BananaMangoFestival You're absolutely right, thanks for pointing this out!

Here's an updated version of the example:

1. Download ```v1.3.6``` _(or higher)_ of the add-on _(right click the download button, save the target)_.
2. Open the downloaded ```.xpi``` archive using your favorite archive manager.
3. Add ```'resources/jqueryui/1.8.16/jquery-ui.min.js.dec': true,``` to ```/lib/files.js```.
4. Create a new folder called ```1.8.16``` inside of ```/data/resources/jqueryui```.
5. Download the [missing file](https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js), add it to the new folder, and name it ```jquery-ui.min.js.dec```.
6. Open the file inside of a text editor, add an ```@``` to the beginning of the file, and save it.
7. Install and start using your custom, unsigned, copy inside of your web browser.

**Comment by BananaMangoFestival** [comment]
It works now! thanks for your job!
So we shall add `@` for each added resource right?
