### ISSUE TITLE
Fetch fonts locally instead of from delivery networks

### ISSUE THREAD

**Issue by mindstormer12** [Synzvato/decentraleyes#105]
Web fonts are a huge privacy concern--many sites use them and as a result, connections are made to third-party domains like Google for their Google Fonts. Is it possible to serve these fonts locally so a connection is not made to the third-party domain? Unlike text fonts where disabling web fonts would simply use other fonts to display the text and you only lose out on aesthetics, disabling web fonts mean you get a meaningless placeholder for iconic fonts such as [Font Awesome](https://en.wikipedia.org/wiki/Font_Awesome) and therefore you lose out on context/usability in addition to aesthetics. 

What's to prevent this from being possible? Could I add my own resources to achieve this?

**Comment by CHEF-KOCH** [comment]
You could:
* Block entirely all external connections by blocking them (uBlock offers an fonts blocking option which blocks @font-face)
* You can block it directly via HOSTS/router
* Google Fonts was never compromised, never ever 
* Blocking them with Firefox
*  Hosting fronts on own or external servers doesn't matter much because it can be compromised on both 
* Non-TTF fonts don't have any known vulnerabilities that I have been able to find, but they may exist.

Problems:
* Font license
* Rendering issue on browsers especially if you disable everything (matter of taste I can live with it)
* There was only two (official problems ever in fonts) see [here](http://technet.microsoft.com/en-us/security/bulletin/ms11-087) & [here](https://technet.microsoft.com/en-us/library/security/ms15-044). I think it's over-hyped and requires additional steps to compromise your security setup anyway.

**Comment by Gitoffthelawn** [comment]
> Google Fonts was never compromised, never ever 

How would anyone know outside of Google?  You can't expect us to trust Google, can you?

Wasn't Google the company that claimed they didn't even know that they were collecting WiFi data packets using their vehicles with special equipment installed that was designed to do just that?

**Comment by CHEF-KOCH** [comment]
Why you distrust everything, makes no sense. Show proof that it was hacked and we can talk about it, but to untrust everything is just paranoid. 

Google is one of the company which changes security related stuff more faster then everyone I know, to name some stuff spdy, sha1, rc4, mail encryption by default and more. 

The documentation of fonts is since the first day here:
https://fonts.google.com/about


Stop been paranoid without anything or wrong _facts_. Geolocation is a huge topic and doesn't have much to do with this topic.

**Comment by Gitoffthelawn** [comment]
Google's actions have provided plenty of good reasons not to trust them.  If you want to cover your eyes and ears, and ignore the facts, that's okay.  But a little research will provide sufficient evidence to not trust them, in my opinion.

Regarding storing resources locally, you have it completely backwards.  Once a resource is stored locally, it is as safe as that system.  Online resources can be modified or exploited at any time.

Anyways, the purpose of this extension is not primarily security, it is primarily privacy, speed, and bandwidth reduction.  I don't think anyone claimed that anyone has ever hacked CDN fonts, although it's certainly possible.

**Comment by CHEF-KOCH** [comment]
* I not ignore something but you bring your personally preferences in this topic. 
* Drive-by is not safer because you simply choose to trust other providers, why they are more secure? The Google fonts was never been hacked, how you hack it btw? This would require to upload infected ones or get anyway _somehow_ access to high restricted servers?! 
* We simply waste developers time with such topics, there is 0% benefit, it not reduce anything and speed up anything (if online <-> online or locally <-> online makes no sense the request is still present), in fact you need more resources, because _another_ addon (this) must be running + it may suffers from known issue (as yourself opened .. the CPU usage issue). 

We can talk about entire day but <code>Web fonts are a huge privacy concern</code> is still wrong. There exist exact 2 issue which was fixed 'more or less fast' but I think HTTP itself have a lot of more issue without any  doubt then this low prio thing.

**Comment by mindstormer12** [comment]
In regards to [licensing](https://developers.google.com/fonts/faq)

**Comment by Gitoffthelawn** [comment]
> We simply waste developers time with such topics, there is 0% benefit, it not reduce anything and speed up anything (if online <-> online or locally <-> online makes no sense the request is still present), in fact you need more resources, because another addon (this) must be running + it may suffers from known issue (as yourself opened .. the CPU usage issue). 

I'm starting to think someone hijacked CHEF-KOCH's account and is using it to troll.

The real CHEF-KOCH would know that most of that is not true.

Besides, if someone sees no value in an extension that *emulates Content Delivery Networks (CDNs) locally by intercepting requests, finding the required resource and injecting it into the environment* (from the README of this project), they should not be using this extension or posting here.

**Comment by Synzvato** [comment]
@stewie This [answer](https://github.com/Synzvato/decentraleyes/issues/100#issuecomment-223826465), is a guide for adding custom libraries. It's almost exactly one month older than your comment, yet you portray me as someone who makes people beg for specific resources.

This add-on is open-source and fully customizable. For a reason.

**Comment by Synzvato** [comment]
@mindstormer12 Thank you for getting in touch! This issue is quite similar to #69, so I'll mark this one as a duplicate. Issue #100 might also be interesting to read as it's about adding custom resources.
