### ISSUE TITLE
Decentraleyes breaks some specific websites

### ISSUE THREAD

**Issue by Nemesis31** [Synzvato/decentraleyes#106]
Hello there,

thanks for your add-on, very useful.

Nevertheless, it's messing with some sites, like https://deathsnacks.com/wf/ (see screenshots below).

**With Decentraleyes**
![decentraleyes_messes_deathsnacks](https://cloud.githubusercontent.com/assets/16542379/16076569/28952306-32f4-11e6-885a-ebf777efef3f.png)

**Without Decentraleyes**
![deathsnacks_without_decentraleyes](https://cloud.githubusercontent.com/assets/16542379/16076617/6aa87bc6-32f4-11e6-840b-bd411951c7a3.png)

Thanks in advance for your respond.

**Comment by Synzvato** [comment]
@Nemesis31 Thanks for sharing your concerns! It's a known bug that is caused by questionable [design choices](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies)<sup>[1]</sup> on the browser's end. Please rest assured that it's being worked on from both sides. Until then, please add any websites that break as a result to your personal whitelist.

You can find it in ```about:addons``` > ```Extensions``` > ```Decentraleyes``` > ```Preferences```.

---

<sup>[1]</sup> [Bug 1256122 - webRequest.onHeadersReceived no redirect to extension page](https://bugzilla.mozilla.org/show_bug.cgi?id=1256122)

**Comment by Synzvato** [comment]
This issue is a duplicate of #16.

**Comment by Nemesis31** [comment]
Thanks for the anwser Synzvato ! Keep the good work ;)

**Comment by Synzvato** [comment]
@Nemesis31 I have decided to create a bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
