### ISSUE TITLE
Improve caching and stop bundling resources

### ISSUE THREAD

**Issue by h1z1** [Synzvato/decentraleyes#108]
Just saw this, looks interesting.   First thing I thought of though was why not change the cache policy on specific URLs rather then store the content outside of the browser?

I've done this for many years, started with my own backend proxy to now nginx.   The difference is most certainly noticeable.  A problem I've had though is trying to maintain an ever growing list of domains.

**Comment by nerdshark** [comment]
The point is that some users don't want to hit those specific URLs at *all*, because said URLs may be used for tracking purposes. CDNs are in prime position for this, as they are used *very* widely. The purpose of extensions like decentraleyes is to help mitigate tracking of users and thus enhance privacy. That decentraleyes does this by providing local versions of these resources is just an implementation detail (albeit a handy one).

**Comment by Synzvato** [comment]
@h1z1 Thanks for sharing your idea, and thank you @nerdshark for your explanation! You should be able to find more details on this under issue #35 (as it's quite similar).
