### ISSUE TITLE
The preferences panel refuses to appear

### ISSUE THREAD

**Issue by jw243** [Synzvato/decentraleyes#141]
Pressing the "preferences" button in Add-ons-Manager just leads to the same desciption page as the "more" button. On this page, however, there are no options for changing preferences, such as "block missing". So how can I change the preferences of decentraleyes?

**Comment by Synzvato** [comment]
@jw243 The preferences should be at the very bottom of the description. If they are not at all present there, I assume that some sort of exception prevents the rendering of the panel. Could you please let me know what exact browser you are using, and what add-ons you currently have installed?

If you're uncomfortable with publishing such details, feel free to send me an e-mail. As a generic tip, you could try restarting your browser into safe-mode to find out if this is caused by an add-on conflict.
