### ISSUE TITLE
Warnings in combination with HTTPS Everywhere

### ISSUE THREAD

**Issue by Johlandabee** [Synzvato/decentraleyes#148]
I get the following warnings in combination with HTTPS Everywhere:
> Warning:
> This extension failed to redirect a network request to https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js because another extension (Decentraleyes) redirected it to chrome-extension://ldpochfccmkkmhdbclfhpagapcfdljkj/resources/jquery/2.0.3/jquery.min.js.dec.

Currently using Chrome but I also got them with Firefox quite a while ago.

**Comment by Synzvato** [comment]
@Johlandabee Thanks for sharing your concerns! In your case, everything is fine. This happened because, as intended, the request was redirected to a local resource. This means that there was nothing left for HTTPS Everywhere to rewrite. The fact that Decentraleyes "wins" here, is a good thing.

People who notice that other add-ons are "winning" against Decentraleyes, should remove and reinstall Decentraleyes. This works, cause redirection races are won by the most recently installed add-on.

> Only one extension is allowed to redirect a request [...] at a time. If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored.

Source: https://developer.chrome.com/extensions/webRequest

**Comment by strugee** [comment]
Seems like there's nothing to be done here, and this issue should be closed?

**Comment by Johlandabee** [comment]
Well,  I'm not sure if there actually can be anything done to avoid those
warnings and fix compatibility with other add-ons trying to redirect
requests.

It does not break anything though but is kind of distracting since chrome
for instance displays an exclamation mark if there is an incompatibility.

If not, the issue should be closed for sure.

Am 10.03.2017 3:37 vorm. schrieb "Alex Jordan" <notifications@github.com>:

**Comment by Synzvato** [comment]
@Johlandabee All valid points. I have looked into what's possible. Enforcing "wins", or preventing add-on warnings is impossible. That's why I have decided to take a different approach, entirely.

Decentraleyes v1.3.7.1 (released minutes ago), automatically sets up a secure connection whenever it is forced to let a request through. You can now safely ask HTTPS Everywhere to ignore CDNs.

Direct link to the newly created FAQ entry with more detailed instructions:

https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-am-i-receiving-https-everywhere-related-warnings-on-chrome-or-chromium

**Comment by war59312** [comment]
Not sure if possible currently.. Sure it is...

Check on install if HTTPS Everywhere is installed and if so automatically open the above link in a new tab.

And have some sort of built in test to be sure the user configured HTTPS Everywhere correctly.

Until the user does that don't allow Decentraleyes to be turned on.

Something like that.

**Comment by Johlandabee** [comment]
@war59312  I wouldn't recommend preventing Decentraleyes from loading. Too much complexity for not too technical versatile users, trust me on that. The warnings do not harm functionality. A notification or hint of some sort, if HTTPS Everywhere is installed, would probably be nice to have.

**Comment by war59312** [comment]
That's true enough. They are just warnings after all.

**Comment by ibrokemypie** [comment]
@Synzvato i love you

**Comment by dlmetcalf** [comment]
I've seen this go the other way:

> Decentraleyes 1.3.7.4
Warning:
This extension failed to redirect a network request to chrome-extension://ldpochfccmkkmhdbclfhpagapcfdljkj/resources/jquery/1.3.2/jquery.min.js.dec because another extension (HTTPS Everywhere) redirected it to https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js.

HTTP Everywhere version is 2017.3.17.

What's the mechanism that determines the browser's filter chain order for extensions?

**Comment by ibrokemypie** [comment]
@dlmetcalf 

> Only one extension is allowed to redirect a request [...] at a time. If more than one add-on attempts to modify the request, the most recently installed add-on wins and all others are ignored.

**Comment by Synzvato** [comment]
@ibrokemypie 

> i love you

![i-know](https://cloud.githubusercontent.com/assets/2366020/24554456/ea5052aa-162d-11e7-8700-52f4b2f1a4e0.png)

**Comment by ibrokemypie** [comment]
hey @Synzvato any chance you could add a link in to the extension itself to that page, or better yet, show that link if errors occur? but of a  pain having to search for it each time i redo browser stuff :/

**Comment by Synzvato** [comment]
Hi @ibrokemypie, I can definitely add a link to the HTTPS Everywhere configuration page. However, I'll not be able to detect any conflicts, as extensions do not get notified when said issues occur. To be able to detect HTTPS Everywhere, we'd need extension administration privileges, which would go too far.

I'll add the link to the configuration page later today. Hope this helps!

**Comment by mikhaelkh** [comment]
Opening [the guide](https://decentraleyes.org/configure-https-everywhere/) I see new rule named [decentraleyes.org](https://www.eff.org/https-everywhere/atlas/domains/decentraleyes.org.html). My guess is I don't need to disable it because doesn't interfere with supported CDNs.

**Comment by Synzvato** [comment]
@mikhaelkh Many thanks for bringing this up! I have updated the configuration guide.

**Comment by rachmadaniHaryono** [comment]
![tooltip_010](https://user-images.githubusercontent.com/6340878/38766435-bcb1e7ee-4004-11e8-85ee-2fe538de6f49.png)
screenshot for httpseverywhere v2018.4.11
