### ISSUE TITLE
Are there differences between this and Local CDN?

### ISSUE THREAD

**Issue by rachmadaniHaryono** [Synzvato/decentraleyes#149]
i got know this extension from this reddit thread. https://www.reddit.com/r/chrome/comments/5y8aha/decentraleyes_just_got_released_for_chrome/

but afaik there is also https://github.com/james-fray/local-cdn, which is a fork(?) of this project, and it created to bring this into chromium. but since decentraleyes have made chrome extension, it make me confused.

is there any difference that local-cdn? should i switch to decentraleyes from local-cdn?

**Comment by Synzvato** [comment]
@rachmadaniHaryono Thanks for getting in touch!

In software engineering, a project fork happens when developers take a copy of source code from one application package and start independent development on it, creating a distinct and separate piece of software. In this case, Local CDN stems from, but is not in any way related to Decentraleyes.

Differences, at the time of writing, include [improved compatibility](https://github.com/Synzvato/decentraleyes/issues/148#issuecomment-285610909) with HTTPS Everywhere, support for a [wide range of languages](https://crowdin.com/project/decentraleyes), and (of course) this being the original codebase.

**Comment by rachmadaniHaryono** [comment]
@Synzvato , thanks for answering, because after i use it, i don't know how it work behind the scene. and as recommended on that reddit thread i also try local-cdn. i don't know how effective between these two, but local-cdn have good ui, where this number shown up wherever any cdn replaced (this related to #145). but after reading this post from yours i will keep decentraleyes for now.

maybe write this in readme? so regular user like me can decide which extension to install.

i think my question is answer, so will close this issue.
