### ISSUE TITLE
Is it possible to reset the injection counter?

### ISSUE THREAD

**Issue by war59312** [Synzvato/decentraleyes#150]
Hi,

Please add a Reset Counter button to the popup and/or options page.

Thanks,

Will

**Comment by Synzvato** [comment]
Hi @war59312, and thanks for sharing the idea. I don't really see why anyone would want to reset the counter, since it's meant to display the amount of injections since the extension was installed. To me, this feels like resetting a car's odometer back to zero. This should be possible, but not too easy, I think.

There is a method to reset the counter, that does not involve reinstalling the extension. This approach should leave any stored preferences intact. You will need to open up the developer tools in the context of the extension.**\*** Once that's done, open up the ```Console``` tab and execute the following line of code:

```js
chrome.storage.local.set({'amountInjected': 0});
```

> **Important:** Disable, and re-enable, the extension immediately after executing the code snippet.

**\*** Firefox users should navigate to ```about:debugging```, and click the corresponding debug link. Chromium users should visit ```chrome://extensions```, tick ```Developer mode```, and click the ```background.html``` link.

**Comment by war59312** [comment]
Good enough. You the man! :D
