### ISSUE TITLE
Why are new permissions needed in Chrome?

### ISSUE THREAD

**Issue by war59312** [Synzvato/decentraleyes#153]
Hi,

Why new permissions needed now in chrome?

Seems it worked fine before.

Thanks,

Will

**Comment by Synzvato** [comment]
I like that you are staying vigilant, and good question! The latest versions need control over your privacy settings in order to prevent content pre-fetching bugs. Decentraleyes' [privacy policy](https://decentraleyes.org/privacy-policy/) still applies.

For transparency, here's all logic involving the newly required permission:

https://github.com/Synzvato/decentraleyes/blob/experimental/manifest.json#L20
https://github.com/Synzvato/decentraleyes/blob/experimental/core/main.js#L20

As the code illustrates, no data will be leaving your machine. Please also note that Chrome displays _both_ of the required permissions during the upgrade, when in fact, only the "privacy" permission is new.

If you have further questions on this, please let me know!

**Comment by LimboSlam** [comment]
@Synzvato: uBloack Origin already has control over this function? However, Decentraleyes took over as of these new permissions. So should I let it be?

**Comment by Synzvato** [comment]
@LimboSlam Good catch! Yes, uBlock Origin and Decentraleyes are mutually compatible.

**Comment by war59312** [comment]
Thank you for the detailed explanation. Much appreciated.

**Comment by war59312** [comment]
Whoops, did not mean to close.

Figured others might be wondering same thing. Will close a bit later once others have had a chance to notice it.

Thanks
