### ISSUE TITLE
Why are new scripts not fetched automatically?

### ISSUE THREAD

**Issue by dlmetcalf** [Synzvato/decentraleyes#156]
Looks like resources aren't automatically updated yet and most in the list are older than current versions of libs (5 months+), so would result in cache misses (end up loaded from the CDN anyway).

Seem like it'd be a LOT of work for you to maintain them all, even if there was a stream of pull requests for new resources.

Have you had thoughts/plans on how best to manage that going forward?  Maybe version ranges would be a solution and optionally prompt the user to pull new resources.

**Comment by dlmetcalf** [comment]
It'd be great to have the option to load or refresh ALL resources over HTTPS from the original sources, at least once.  (Maybe compare downloaded versions against stored hashes distributed with the extension and flag any that don't match).

The code for the extension itself isn't huge, so could be audited. But manually auditing all the new resources each time there's an update doesn't sound too feasible.

Don't take this personally, but if a 3rd party (user) is being professional paranoid, having to trust that every resources you've installed is untainted and that your development environment is highly secure and never compromised (i.e. some resource hasn't been injected with bitcoin miner or whatever), has a wider margin of exposure.

A user could build everything for themselves locally, but most won't.

What are your thoughts?  Do you think a download/refresh mechanism would be viable?

(I know that if resources could be hacked, so could download or hash/sig comparison mechanism, but at least it's far less code to check and should relatively infrequently).

**Comment by Synzvato** [comment]
> Looks like resources aren't automatically updated yet and most in the list are older than current versions of libs (5 months+), so would result in cache misses (end up loaded from the CDN anyway).

Thanks for sharing your thoughts on the current library bundle! The reason why this package doesn't necessarily contain the most recently released versions of libraries, is that it's based on [usage statistics](https://w3techs.com/technologies/overview/javascript_library/all) by W3Techs. We're targeting the most commonly used versions, instead of all most recent ones.

> Seem like it'd be a LOT of work [...], even if there was a stream of pull requests for new resources. Have you had thoughts/plans on how best to manage that going forward?

I am happy to say that this is a non-issue. In reality, not too many website owners decide to upgrade their libraries (frequently) when things are working well. This gives us a fair bit of breathing room.

> It'd be great to have the option to load or refresh ALL resources over HTTPS from the original sources, at least once. (Maybe compare downloaded versions against stored hashes [...]).

We're starting to register all bundled resources as being "web accessible". The corresponding manifest entry is static. To cut a short story _even shorter_, dynamically loading in resources is tricky. In the future, it _might_ be possible to allow users to add files from local folders (if they accept file URL permissions).

> The code for the extension itself isn't huge, so could be audited. But manually auditing all the new resources each time there's an update doesn't sound too feasible.

That is a very valid point. I'd like to point out that every single copy of Decentraleyes comes with an  [audit script](https://github.com/Synzvato/decentraleyes/blob/09a02eb5f345baf7774c4dc7e4605e31832feba0/data/_audit/run.js), anyone can run locally to verify bundled resources. It's also used by moderators at Mozilla.

Thanks again, and I hope this answers your question!
