### ISSUE TITLE
Legacy extension breaks the Zomato website

### ISSUE THREAD

**Issue by savyajha** [Synzvato/decentraleyes#189]
Decentraleyes being enabled breaks the loading of certain images on zomato.com

**How it should be:**

![screenshot-2017-8-27 restaurants - chandigarh restaurants restaurants in chandigarh zomato india 1](https://user-images.githubusercontent.com/3996019/29753198-9115193e-8b5b-11e7-8918-45cb6637a51b.png)

**How it actually is:**

![screenshot-2017-8-27 restaurants - chandigarh restaurants restaurants in chandigarh zomato india](https://user-images.githubusercontent.com/3996019/29753211-ae630b04-8b5b-11e7-9a4f-d382043a674e.png)

I've tested this with a fresh profile with nothing but decentraleyes installed. Disabling it causes the images to load, as in the first screenshot, and enabling it causes the images to not load, as in the second one. Seeing that the site is all about finding and reviewing restaurants, the lack of images is quite a blow to usability.

**Comment by Synzvato** [comment]
Thanks for sharing your concerns!

Based on your findings, I am asuming you are currently using the ```legacy``` extension for Firefox. As a quick fix, you could add ```zomato.com``` to the extension's whitelist. The issue will be fixed in the next major release (that's currently in beta). You can find the whitelist preference inside ```about:addons```.

I hope this helps! If you have any additional questions, be sure to get in touch.

**Comment by savyajha** [comment]
Thank you so much! I will do as you ask, and will update the issue upon getting the next version.

**Comment by savyajha** [comment]
All right, so the webextension solves this issue. Thank you very much! :)
