### ISSUE TITLE
Will this add-on continue to support Pale Moon?

### ISSUE THREAD

**Issue by LimboSlam** [Synzvato/decentraleyes#190]
Hi there @Synzvato, will Decentraleyes continue to support Pale Moon further, or has it ended? Currently, we are stuck on v1.3.7 and v1.3.10 is out. Now, if support has already ceased, then is it safe to continue using v1.3.7? 

Thanks for all your help, and keep up the good work. :+1:

**Comment by Synzvato** [comment]
Hi @LimboSlam. The latest update ```v.1.3.10``` does not bring anything useful to Pale Moon. It migrates legacy settings to an embedded dummy of the upcoming Firefox ```WebExtension```.

However, in order to ensure continued compatibility with browsers such as Pale Moon, this feature only activates if there is support for "Embedded WebExtensions". There is full backward compatibility.

Since I understand that the version gap might give Pale Moon users the idea that the add-on is no longer supported, I have decided to push the ```v1.3.10``` update into Pale Moon's add-on repository.

Thanks for sharing your concerns, and I hope this answers your questions!

**Comment by LimboSlam** [comment]
Thanks! It has.

**Comment by LimboSlam** [comment]
@Synzvato, It has always kept me wondering, but I never like coming off rude. So I will just ask: 

Why doesn't Decentraleyes have a GUI for the Pale Moon browser, yet? And will there be a feasible future to provide that luxury?

**Comment by THEtomaso** [comment]
I'd also like to add my voice here, pointing out the need for an XUL/XPCOM version update.
The number of Pale Moon users continues to grow, and since a large part of its users tend to be much more privacy-focused than the average FF user, Decentraleyes is indeed a sought-after extension!

**Comment by sergeevabc** [comment]
Please, roll out the update for Pale Moon users.

**Comment by RoestVrijStaal** [comment]
It turns out Pale moon users are on their own and likely need to fork DecentralEyes to resolve #269 and #170 nowadays.

**Comment by THEtomaso** [comment]
Actually, neither one of those bugs seems to affect my setup, using Pale Moon v27.9.0,x64 + Decentraleyes v1.3.10.
