### ISSUE TITLE
Shorthand URL notations cause page freezes

### ISSUE THREAD

**Issue by jingyu9575** [Synzvato/decentraleyes#192]
Decentraleyes 2.0.0beta1 WebExtension on Firefox Nightly 2017-08-29.
If the CDN resource does not have explicit URL scheme (e.g. `<script src="//code.jquery.com/jquery.min.js"></script>`), the page freezes.
Example: https://jsfiddle.net/xm1tza0d/3/  and  https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by Synzvato** [comment]
Hi @jingyu9575, and many thanks for sharing your detailed findings!

After a thorough debugging session, I have found that the issue has less to do with implicit ```URL``` schemes, and more with shorthand ```URL``` notations. Your examples really helped to reproduce the bug.

The problem is actually caused by shorthand notations that feature implicit version details. For example, ```/jquery.min.js``` and ```/jquery-latest.min.js``` both correspond to ```v1.11.1```. You might notice that jQuery ```v1.11.1``` is far from the latest version. That's because implicit versioning has since been deprecated.

So, luckily, they're quite uncommon nowadays. I agree that this fact is no valid reason not to support them, and that's why I have been working on a fix (see commit b45df1f03200dbe2f6b49b81e366575fa36d4072). Would you be willing to pull in the code to verify that it solves your problem? If so, could you also test the fix on [this example](https://decentraleyes.org/4d1692e7dd6c2581/)?

**Comment by jingyu9575** [comment]
I have tested the latest master branch (after b45df1f). All the 3 examples work now. 

> WEBPAGE DID NOT FREEZE.
> LIBRARY IS AVAILBLE.

decentraleyes.org/test shows "Decentraleyes is fully operational".
Thanks!
