### ISSUE TITLE
[beta] Popup cut off when extension icon moved to "More tools…" menu

### ISSUE THREAD

**Issue by jomo** [Synzvato/decentraleyes#202]
I'm not sure if this is a bug in Firefox or in Decentraleyes. When the extension icon is moved into the "More tools…" menu in Firefox 57, the popup is cut off at the side, see screenshot:

![screenshot](https://user-images.githubusercontent.com/3585743/30941686-fbac4792-a3e6-11e7-8fb7-4ce934ea174a.png)

This is happening because the menu opens with a certain width and doesn't resize when it switches its content to that of the extension popup.

Is Firefox supposed to resize the popup, is the extension supposed to do that on its own, or is the extension supposed to support the smaller width?

**Comment by jomo** [comment]
Just found [this](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing) 5 minutes later:

> Popups resize automatically to fit their content. […] Firefox calculates the preferred width of the contents of that element, reflows it to that width, and then resizes so there's no vertical scrolling. […] **If the user moves the extension's button to the menu or it appears in the toolbar overflow, then the popup appears inside the menu's panel and is given a fixed width.**

As I understand it, Decentraleyes would be supposed to support this fixed width.

**Comment by Synzvato** [comment]
Hi @jomo, and thanks for reporting the issue!

Could you please let me know what the browser preference ```layout.css.devPixelsPerPx``` is set to on your side? I was able to reproduce the problem by changing its value from ```-1.0``` to ```1.1```.

**Comment by jomo** [comment]
It's `-1.0` for me, using a retina display. Changing the value has no effect other than scaling the whole browser UI, the popup is still cut off.

**Comment by Synzvato** [comment]
@jomo Thanks! So, the bug is probably caused by the fact, that the "fixed width" popup has problems with non-default pixel densities. I'll see what I can do. I also noticed that Firefox forcefully chopping off the bottoms of "fixed width" popups. This is likely a browser bug, as all extensions I tested were affected.

**Comment by jomo** [comment]
Are you sure? The popup is 320px for me in the latest (57.0b3) Firefox Developer Edition, but popup.css [apparently](https://github.com/Synzvato/decentraleyes/blob/a45c55b4d40e5c5bf4571f898c5cea00a2075ff5/pages/popup/popup.css#L14) sets the body width to 348px.

I also have the issue with popups being cut off at the bottom when moving extensions to the menu, but the popup height resizes after (guessed) half a second.

**Comment by jomo** [comment]
Changed that line to 320px and it seems to fixed, I guess the popup width is just 320 then… Is it different for you?

![screenshot](https://user-images.githubusercontent.com/3585743/30949270-a547ddc4-a415-11e7-9fac-759703db3640.png "320px")

**Comment by Synzvato** [comment]
> I guess the popup width is just 320 [...]. Is it different for you?

@jomo Yes, ironically, the "fixed-width" popup container is ```348px``` instead of ```320px``` on my end. That's also why this exact width was chosen to begin with. Since this is reproducible by altering pixel sizes, or by resizing the container, I think your solution should do the trick. Many thanks for your contribution!

I will test the change on both desktop and mobile, and will get back to you as soon as that's done. As for the display issue that affects any embedded popup footer, this is what I'm experiencing on my end:

![image](https://user-images.githubusercontent.com/2366020/30967310-edc39f84-a429-11e7-9869-1e976a2f161d.png)
> The embedded popup before and after applying a custom style rule.

In order to fix this issue, you currently need to tweak browser chrome styles. I was able to restore the footer by assigning ```max-height: unset !important;``` to ```.PanelUI-subView[extension="true"]```. So, it appears that the "More Tools" menu is not quite there yet. Here's another display issue:

![image](https://user-images.githubusercontent.com/2366020/30967761-3acb6b8a-a42b-11e7-9360-2eaa5cf47f45.png)
> A badge spacing issue that affects all tested extensions.
