### ISSUE TITLE
Add support for the Google Static service

### ISSUE THREAD

**Issue by EC-O-DE** [Synzvato/decentraleyes#207]
More CDN's to Decentraleyes?

Like gstatic.com for example? And many more..

Why so little amount?

**Comment by PeterDaveHello** [comment]
> Why so little amount?

I bet it's the complexity and effort, overhead to maintain and use this project, it's trade off.

**Comment by EC-O-DE** [comment]
Hmm, well a bit more more some of the most popular? Errr Bootsrap? heh.. 

I think that other ext "local CDN" gives a long list of what it includes, despite this ext has quite the same amount... So perhaps generate a list for Decentral too?

**Comment by Synzvato** [comment]
> More CDN's to Decentraleyes? [...] Like gstatic.com for example? [...] Why so little amount?

Since there is little fragmentation when it comes to JavaScript CDNs, blocking the currently supported key players, solves a large part of the problem. Please see these [market share statistics](https://w3techs.com/technologies/overview/content_delivery/all) by W3Techs.

> I think that other ext "local CDN" gives a long list of what it includes

There's no mention of ```gstatic.com``` in Local CDN's list of supported Content Delivery Networks. What corresponding resources would you like to see mapped? Note that it's essential that all bundled resources are strictly versioned. All I see is the addition of three players with little to no market share.

**Comment by EC-O-DE** [comment]
Hmmm well these are what are extra on Local CDN:
cdn.bootcss.com
cdn.css.net
cdn.staticfile.org

AND they list these:
angular
backbone
dojo
ember
extCore
jQuery
jQueryUI
modernizr
mootools
prototypeJS
scriptaculous
swfobject
underscore
webfont

Anything to add?

**Comment by EC-O-DE** [comment]
https://developers.google.com/chart/interactive/docs/basic_load_libs

**Comment by EC-O-DE** [comment]
We should get as much as possible: Google to local!

Decentralize!

**Comment by Kasijjuf** [comment]
Create a GitHub issue for each CDN you would like to be supported. Having this GitHub issue nonspecifically requesting "more CDNs" is not helpful and just creates noise in the issue tracker.

**Comment by EC-O-DE** [comment]
Like, google has several locations where they share they're API's and contents. Not just the one included. + gstatic...

**Comment by Synzvato** [comment]
@EC-O-DE I will be closing this issue. However, feel free to re-open it, in case you have a concrete list of strictly versioned ```gstatic.com``` resources you'd like to nominate. Thanks for sharing your thoughts!
