### ISSUE TITLE
2.0 breaks stackoverflow voting

### ISSUE THREAD

**Issue by azrdev** [Synzvato/decentraleyes#208]
running Firefox 56 with Decentraleyes 2.0.0 (also `uBlock Origin` 1.14.14, `RequestPolicy Continued` 1.0beta13.1, and `HTTPS Everywhere` 2017.10.4).

Since the update to 2.0 stackoverflow shows its red warning "Stack Overflow requires external JavaScript from another domain, which is blocked or failed to load." whenever DC is enabled for the domain. Generally, the site seems to work, except for voting on answers (needs logged in user, obviously), which does nothing.

**Comment by Synzvato** [comment]
Thanks for sharing your concerns!

Since I am unable to reproduce your problem, I'm assuming that one of your regular content blockers is blocking requests to ```ajax.googleapis.com```. Have you tried following [these instructions](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on)?

**Comment by EC-O-DE** [comment]
They just switch to www.googleapis.com instead.

**Comment by azrdev** [comment]
@Synzvato 
> Since I am unable to reproduce your problem, I'm assuming that one of your regular content blockers is blocking requests to ajax.googleapis.com. Have you tried following these instructions?

That's why I disabled blocking in all of them to check whose fault it is, and only enabling/disabling DC makes a difference.
Also I followed these instructions, adding the list (including `ajax.googleapis.com`) to the uBlock exceptions. RequestPolicy already had the domain allowed.

@EC-O-DE sorry, what do you want to tell us?

**Comment by Synzvato** [comment]
@azrdev

> RequestPolicy already had the domain allowed.

After recreating the environment you described in your original comment, I was able to reproduce the problem. As it turns out, RequestPolicy Continued cannot be completely disabled using its own interface, since your issue no longer occurs after said extension has been disabled from within ```about:addons```.

Could you please let me know if completely disabling the add-on fixes the problem?

**Comment by azrdev** [comment]
@Synzvato I can confirm exactly as you said, thanks for triaging!

**Comment by azrdev** [comment]
thank you!

**Comment by Synzvato** [comment]
I can confirm that ```1.0.beta13.2``` still breaks under the conditions described by @YtvwlD in #226. In case you are experiencing similar problems, please see the temporary workaround described below.

1. Navigate to ```about:config```, and accept the risks).**\***
2. Set ```extensions.alwaysUnpack``` to ```true```.
3. Completely remove and reinstall Decentraleyes ```2.0.0```.
4. Set ```extensions.alwaysUnpack``` back to ```false```.

**\*** Only if you're actually willing to accept them, of course.

This should help circumvent any issues RequestPolicy Continued currently seems to have, with requests that are redirected to compressed, local, resources. I hope this helps! If not, please do let me know.
