### ISSUE TITLE
Update #6 for FAQs

### ISSUE THREAD

**Issue by Rictusempra** [Synzvato/decentraleyes#210]
![image](https://user-images.githubusercontent.com/16912240/31582483-d6b8682a-b1b6-11e7-8c4c-73746a8a92de.png)

This can be also likely to happen in Firefox Web Extension.
But since that HTTPSEverywhere is still legacy now, this can be not high priority.

**Comment by Xorok** [comment]
The WebExtension version of HTTPS Everywhere has been available for testing for some months on the EFF's official website. I've been using it since quite some time, and it works well.

https://www.eff.org/https-everywhere (scroll down to **Developers**)
https://www.eff.org/files/https-everywhere-test/index.html

**Comment by Kasijjuf** [comment]
The WebExtension version of HTTPS Everywhere is now the current stable release.

**Comment by Synzvato** [comment]
Hi @Rictusempra, and thanks for voicing your concerns. I have been testing the behavior extensively, and can only conclude that this does not affect Firefox. Installing both add-ons should not cause request leakage. Even if you install HTTPS Everywhere last. I hope this helps! If not, please do let me know.

Thank you for the feedback and updates, @Xorok and @Kasijjuf. So, based on what read here, in combination with my personal findings, I think it's safe to close this issue. However, anyone is free to re-open it when necessary, so be sure to ring the bell in case your conclusion differs from mine.
