### ISSUE TITLE
Breaks when used alongside HTTPS Everywhere

### ISSUE THREAD

**Issue by jony0008** [Synzvato/decentraleyes#216]
I got this warning today (below), it is in English but I hope you can figure out what it says. I means that Decentraleyes was unable to redirect the network request because HTTPS Everywhere redirected it.

Det gick inte att omdirigera nätverksbegäran till chrome-extension://ldpochfccmkkmhdbclfhpagapcfdljkj/resources/jquery/1.8.3/jquery.min.js.dec eftersom ett annat tillägg (HTTPS Everywhere) omdirigerade det till https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js.

**Comment by Synzvato** [comment]
Hi @jony0008, and thanks for sharing your concerns! Please follow this [brief guide](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-am-i-receiving-https-everywhere-related-warnings-on-chrome-or-chromium), to prevent any further conflicts. I hope this solves your problem. If not, feel free to post a reply under related issue #148.

**Comment by gitressa** [comment]
With Firefox 57 it seems like you have to untick all checkboxes within the "Stable rules" section, and leave "decentraleyes.org" checked, just as with Chromium, Chrome, and Opera.
https://decentraleyes.org/configure-https-everywhere/

**Comment by Synzvato** [comment]
@gitressa Thanks for getting in touch! What makes you think that Firefox 57 is equally affected? I would be happy to look at any supporting findings, as I have been unable to reproduce the issue.

**Comment by gitressa** [comment]
@Synzvato You're welcome, thanks for making the add-on for Firefox! My previous comment was probably wrong. The reason I thought it didn't work was because https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js was loaded when visiting http://politiken.dk/nyheder/.
Enabling "Block requests for any missing CDN resources" fixed it, and looking under [jQuery script resources for Decentraleyes](https://github.com/Synzvato/decentraleyes/tree/master/resources/jquery) it seems like that version of jQuery is not included, the last one being 2.1.4. Do you think it's worth considering adding some of the more recent versions of [jQuery libraries](https://code.jquery.com/jquery/)?

**Comment by Synzvato** [comment]
@gitressa I'm glad to hear everything is working as intended! As for ```jQuery```, please see [this comment](https://github.com/Synzvato/decentraleyes/pull/215#issuecomment-338325522).

**Comment by gitressa** [comment]
Thanks for the link, I look forward to jQuery 3 getting included, and thanks to @ExE-Boss for creating the pull-request.
