### ISSUE TITLE
Should we petition for new webfont standards?

### ISSUE THREAD

**Issue by hdatma** [Synzvato/decentraleyes#220]
Let me know if this makes sense to you. 

Problem: 
1. webfonts are a well-known security risk; 
2. webfonts are a waste of bandwidth; 
3. webfonts leave meaningless spaces when their remote resource is broken|blocked; 
4. problem 3 occurs also on Firefox extensions ("uBlock origin", "cookie autodelete"). 

Proposed Solution:
W3C ought to take us out from the misery they put us in, by defining a standard set of *names* and *meanings* for webfonts/icons, so that default local resources intervene when the remote ones are not available (or blocked). 

If it makes sense to you, let us organize a petition...

**Comment by Synzvato** [comment]
Hi @hdatma, and thanks for sharing your thoughts! The way I'm reading this, it seems that you're mainly interested in encouraging the ```W3C``` to cook up a naming standard for popular, web-based, icon fonts.

> [...] webfonts leave meaningless spaces when their remote resource is broken|blocked;

This is the argument that gave me the impression you're primarily referring to icon fonts. Most traditional webfonts should fall back to ```serif```, ```sans-serif```, or ```monospace```, instead of leaving empty spaces.

> W3C ought to take us out from the misery [...], by defining a standard set of names and meanings for webfonts/icons, so that [...] local resources intervene when the remote ones are [...] blocked [...].

I would be inclined to agree with you, if it wasn't for the fact that:
1. popular web icon toolkits are currently [moving away](https://fontawesome.com/get-started) from webfonts;
2. a standard for linking fonts to basic font families [already exists](https://www.w3.org/TR/CSS21/fonts.html#generic-font-families).

As soon as bug [```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459) on Mozilla's bugtracker has been resolved, additional resources can be added to this extension's resource bundle. I'm happy to say that Font Awesome is [at the very top](https://github.com/Synzvato/decentraleyes/issues/37#issuecomment-180770678) of the list.

Please do get back in touch; especially if you feel that I'm overlooking something vital.

**Comment by hdatma** [comment]
Our privacy and security policy, that we enforce by law on all of our clients, blocks remote icons and fonts, forcing FF to use local resources only. The side effect of this is, that firefox leaves ugly and meaningless "broken icon" for firefox extensions, bank and government sites. This is especially irritating when the broken icon is red, signalling a problem of unknown content. There is no way to know the meaning of those broken icons, unless you allow for their remote resource. There is no standard for such icons: anybody can make up their own. (I referred to web icons as web fonts because the icons I spoke about are  defined as fonts and use the same technology of fonts.)

**Comment by hdatma** [comment]
Decentraleyes could intervene, in its role, but it cannot replace icons at random, hence the need for standard names and their meaning. If a bank uses a fancy name for a fancy red alert of their own, and you disabled the web font engine, neither firefox nor decentraleyes could guess a correct replacement.

**Comment by hdatma** [comment]
The problem is similar to the problem of blind persons trying to read a webpage that was not designed for them. The paradox is, that a plain text page is far more informative than a fancy graphical one.
