### ISSUE TITLE
Add support for Cloudflare-related CDNJS

### ISSUE THREAD

**Issue by jonazc** [Synzvato/decentraleyes#222]
Some don't get jquery from google but from cloudflare, like sslabs: https://www.ssllabs.com/ssl-pulse/ I don't know if there are also other stuffs hosted at cdnjs subdomain that could be worth to store locally.

**Comment by Synzvato** [comment]
Hi @jonazc, and thanks for sharing your thoughts! I'm happy to say that the CDNJS network is already supported. The problem is that Qualys SSL Labs self-hosts jQuery ```v1.11.0```, but pulls a separate library called jQuery Tools from said CDN. This library holds jQuery ```v1.7.1```, along with various ```UI```-tools.

I'm not entirely sure what they were going for here, as it seems that their self-hosted copy of jQuery is directly overwritten by the older copy included inside of the third party script. In any case, Decentraleyes supports CDNJS when it comes to regular jQuery releases. Selections are based on market share.

**Comment by jonazc** [comment]
I see. Unfortunately I just experienced another problem because of this. Following the [FAQ](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#for-umatrix-and-ublock-origin-non-easy-mode-users) I added (besides others) the rule 

* cdnjs.cloudflare.com * noop

to Umatrix. But now, it also allows to load this script actually from the server and not locally. Thats a problem, that we allow the whole domain in umatrix but decentraleyes catches only specific scripts.

**Comment by Synzvato** [comment]
Please make absolutely sure that you have followed all [related instructions](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#for-umatrix-and-ublock-origin-non-easy-mode-users), and especially:

> **Important:** Enable [...] _block requests for missing resources_ [...] inside the Decentraleyes extension ```Options``` screen, in order to reinstate [...] strict CDN-blocking policies.

**Comment by EC-O-DE** [comment]
I'm not sure would blocking missing resources brake stuff around. Perhaps I'll test and see :)

**Comment by jonazc** [comment]
> block requests for missing resources

ah ok, thanks, I missed that

**Comment by jonazc** [comment]
oh yes but @EC-O-DE is true, I cant manage the block then using uMatrix, so I can't unblock it, thats pretty bad. Decentraleyes really should be part of umatrix :P

**Comment by Synzvato** [comment]
> oh yes but @EC-O-DE is true [...]

Yes. That's why it has been labeled advanced, and is disabled by default. It's comparable to non-easy modes in uBlock Origin, and to uMatrix as a whole. Use it if you prefer control over convenience.

> I cant manage the block then using uMatrix [...].

You can definitely manage your CDN-traffic using uMatrix, instead of through Decentraleyes. Simply remove the check in front of _block requests for missing resources_, and remove all whitelisting rules you were asked to add  to uMatrix. When done, requests will no longer be delegated to Decentraleyes.

You will lose the added benefit of verified local scripts being able to run automatically. In essence this means more tinkering with website specific blocking rules. This will definitely work, though.

> [...] I can't unblock it, thats pretty bad.

That _would be_ pretty bad, but in fact, you actually can; uMatrix shows you a list of domains the website wants you to connect to. In case you need to unblock CDN-domains, just use the whitelist button.

![image](https://user-images.githubusercontent.com/2366020/33017917-086c3d82-cdd3-11e7-8e3e-61bbdd94e771.png)
