### ISSUE TITLE
Will the WebExtension support Firefox 52 ESR?

### ISSUE THREAD

**Issue by Tallefer** [Synzvato/decentraleyes#223]
Hello.
Just to clarify things:
It seems odd that there are no talks about ESR 52 support anywhere in issues, only about Palemoon (but that's a bit different beast). However, I saw "ESR" link from the main page, which explicitly points to version 1.3.10, but the question still stands:
Will Decentraleyes versions 2+ support Firefox 52 ESR? Webextensions engine is there, if I am not horribly mistaken, of course.

Issue is partly connected to #211 and #190 
Please keep this issue open until/unless the answer is in the FAQ or somewhere clearly visible.
Thank you for your work!

**Comment by Synzvato** [comment]
Hi @Tallefer, and thanks for getting in touch. I'll try my best to clear up any confusion.

> Will Decentraleyes versions 2+ support Firefox 52 ESR? Webextensions engine is there [...].

Decentraleyes relies on APIs that are only present in Firefox 56 and higher. Dropping support for lower versions was absolutely [necessary](https://github.com/Synzvato/decentraleyes/issues/173#issuecomment-325745029). Since ESR users are typically fine with missing out on new features, in exchange for stability, I see no issues there. The next ESR will meet the minimum requirements.

> Please keep this [...] open until/unless the answer is in the FAQ or somewhere clearly visible.

The reason it's not in the FAQ, is because it's not a commonly asked question. Quite a few people did get in touch to inquire on _what_ to install when using Firefox ESR. That's why the instructions were added.

> Thank you for your work!

My pleasure, and I'm happy to hear you appreciate the extension!

**Comment by Tallefer** [comment]
Ah, I see now. It's a shame that needed parts are not in 52 ESR. Any clues if they will get there eventually?

**Comment by Synzvato** [comment]
> Ah, I see now. It's a shame that needed parts are not in 52 ESR. Any clues if they will get there [...]?

From what I can tell, the chances of that happening are very close to non-existent. If possible, it might be best to wait until March of next year. That's when Firefox 59 ESR will become available.
