### ISSUE TITLE
Add React library files to the resource bundle

### ISSUE THREAD

**Issue by bishtawi** [Synzvato/decentraleyes#23]
Needs React.js files: https://cdnjs.com/libraries/react/
Should include react, react-dom (0.14+) and react-with-addons

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
anyway to do this our selves? this ticket has been open a long time with no response.

Thanks!

**Comment by Synzvato** [comment]
@L-a-n-g-o-l-i-e-r-s Of course. Feel free to download any known CDN libraries you like, strip out source map comments, add them to ```files.js```, map file locations in ```mappings.js```, and test your mappings by writing some test cases. Make sure your Firefox installation lets you install unsigned add-ons.

> this ticket has been open a long time with no response.

It's a community project. Which means anyone is welcome to submit web crawling statistics (essential for finding out if something is worth adding), and contributing helpful comments and Pull Requests.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
Ah I figured it wouldn't be as simple as dragging, dropping, repackaging and installing, even with the extension as it is now. I wouldn't know where to start. Thanks for your response, I gather that someone more qualified might find your post welcoming and wish to contribute based on it.

**Comment by Synzvato** [comment]
I see, thanks for your willingness to help out in any case! Adding new libraries and mappings is not the most intricate part though. It's very important that the add-on stays as light-weight as possible. That's why I cannot add resources before witnessing any encouraging web crawling statistics.

View #45 to see, amongst other things, React's current market share.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
That explains a lot.
