### ISSUE TITLE
Update FAQ to avoid unwanted permanent rules

### ISSUE THREAD

**Issue by jonazc** [Synzvato/decentraleyes#231]
It looks like the umatrix list in the Wiki FAQ still provides an old format, `noop` should be `allow` as far I understand it.

https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions

Furthermore, the description how to add the whitelisted domains contains a small "bug". Because it should be mentioned that ALL temporary rules that has recently be made in the browser session will be saved permanently when following the steps proposed in the description. Not only the manually added whitelist. So one should restart the browser and remove all temporary rules before adding the whitelist manually.

**Comment by anarcat** [comment]
this could be fixed by the community if the wiki was editable.

**Comment by jonazc** [comment]
indeed :)

**Comment by puff-m-d** [comment]
Hello,

Here is what I use for uMatrix:

* ajax.aspnetcdn.com script allow
* ajax.googleapis.com script allow
* ajax.microsoft.com script allow
* cdn.jsdelivr.net script allow
* cdnjs.cloudflare.com script allow
* code.jquery.com script allow
* lib.sinaapp.com script allow
* libs.baidu.com script allow
* upcdn.b0.upaiyun.com script allow
* yandex.st script allow
* yastatic.net script allow

**Comment by Synzvato** [comment]
> this could be fixed by the community if the wiki was editable.

This is actually a great example as to why it's good that the list of answers to frequently asked questions isn't publicly editable. It used to be, until people started inserting ```TODO``` comments into the answers.

> It looks like the umatrix list in the Wiki FAQ still provides an old format

Not really, it uses an exchangeable format that works for both related extensions. So, this has nothing to do with this being "an old format"; uBlock Origin accepts it, and uMatrix defaults it back to ```allow```.

> Here is what I use for uMatrix [...]

That is indeed what you would want to see, and what you will end up with after following the instructions.

> Furthermore, the description [...] contains a small "bug". Because [...] ALL temporary rules [...] will be saved permanently when following the steps proposed in the description.

This is definitely the most interesting part of the proposal, @jonazc. Since it's a small issue, it has been prioritized accordingly. Many thanks for reporting this, and know that it will be looked into!

**Comment by Synzvato** [comment]
The FAQ has since [been amended](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions/859c356621d4ddf45c6d75051194cfcdfafaddee), to prevent unwanted commits. Thanks again for reporting this!
