### ISSUE TITLE
Do webpages load faster with this extension?

### ISSUE THREAD

**Issue by DesWurstes** [Synzvato/decentraleyes#234]

**Comment by Synzvato** [comment]
Even though this is a privacy and security extension, it was built with performance in mind. A lot of the tasks are performed asynchronously, which means they do not block other actions. Tasks that do block other actions have received a fair bit of special care with regards to performance optimization. 

In case you're planning to use Decentraleyes as a speed booster, instead of a privacy tool, you might want to take a gander at the ```Options``` page. The extension allows you to maximize performance at the expense of privacy protection.* As for library injections, it's pretty hard to beat local file delivery.

\* If you're purely interested in the speed improvements, disable both ```Disable link prefetching```, and ```Strip metadata from allowed requests```. Should you, at all, care about the privacy improvements, then I do not advise you disabling the protection measures. The extension should perform great either way.

Personally conducted tests are indeed confirming the expected performance improvements. With all privacy protection features enabled, that is. The advantages might, or might not be, highly noticeable on your end. It mostly depends on your setup, and network latency. I hope this answers the question!

**Comment by EC-O-DE** [comment]
Opera/Chrome doesn't have those settings^ ...?

**Comment by Synzvato** [comment]
@EC-O-DE Said options were introduced in ```v2.0.0```. This means that they are in fact present in the latest Chrome release. The Opera-release has been submitted, but is still awaiting moderation.
