### ISSUE TITLE
Is Decentraleyes compatible with referrer spoofers?

### ISSUE THREAD

**Issue by BillyJoeJimBob** [Synzvato/decentraleyes#240]
Is there any benefit or detriment to running Decentraleyes together with a referrer remover/spoofer like Referrer Control and/or a link cleaner/UTM stripper such as Pure URL?  Does Decentraleyes render any of them redundant or will they possibly conflict?  It's not clear to me whether referrers or tracking tokens matter if Decentraleyes is handling local CDNs. Chrome indicates that Decentraleyes sometimes conflicts with Referrer Control, but I haven’t noticed any problems.  -Thank you.

**Comment by Synzvato** [comment]
Hi @BillyJoeJimBob, and thank you for getting in touch!

> Is there any benefit or detriment to running Decentraleyes together with a referrer remover/spoofer like Referrer Control [...]? Chrome indicates [...] conflicts with Referrer Control [...].

It's perfectly fine to use a referrer extension alongside Decentraleyes. The conflicts you noticed occur, because both extensions attempt to strip metadata from allowed CDN-requests. You can tell the referrer extension to ignore supported CDN-domains, or disable ```Strip metadata from allowed requests```.

> Is there any benefit or detriment to running Decentraleyes together with [...] a link cleaner [...]?

No, not at all. You should be able to combine these types of extensions without issue.
