### ISSUE TITLE
There are various resource hints and directives

### ISSUE THREAD

**Issue by EC-O-DE** [Synzvato/decentraleyes#277]
A lot of!
https://www.keycdn.com/blog/resource-hints/

**Comment by criztovyl** [comment]
I see no reason for the current down-vote, the issue is just providing information.

I also think that the mentioned resource hints are within a bigger scope that Decentraleyes cannot fill alone.

But IIRC all the things mentioned in the blog article can be disabled by via prefs in `about:config`.

**Comment by criztovyl** [comment]
See "Prefetching" in [How to stop Firefox from making automatic connections](https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections) (support.mozilla.org).

**Comment by CHEF-KOCH** [comment]
Prefetch or pre-connection can be since over 3 years configured in Chrome, dunno about how long in Firefox via about:config but at least 2 years. 

```
enum ResolutionMotivation {
    MOUSE_OVER_MOTIVATED,     // Mouse-over link induced resolution.
    PAGE_SCAN_MOTIVATED,       // Scan of rendered page induced resolution.
    LINKED_MAX_MOTIVATED,      // enum demarkation above motivation from links.
    OMNIBOX_MOTIVATED,          // Omni-box suggested resolving this.
    STARTUP_LIST_MOTIVATED,   // Startup list caused this resolution.
    NO_PREFETCH_MOTIVATION,  // Browser navigation info (not prefetch related).
    EARLY_LOAD_MOTIVATED,     // In some cases we use the prefetcher to warm up the connection
                                            // in advance of issuing the real request.
    UNIT_TEST_MOTIVATED,

    // The following involve predictive prefetching, triggered by a navigation.
    // The referrinrg_url_ is also set when these are used.
    STATIC_REFERAL_MOTIVATED,     // External database suggested this resolution.
    LEARNED_REFERAL_MOTIVATED,  // Prior navigation taught us this resolution.
    SELF_REFERAL_MOTIVATED,        // Guess about need for a second connection.
    MAX_MOTIVATED                      // Beyond all enums, for use in histogram bounding.
  };
```

```
// Chrome (Chrome itself uses the integrated DNS resolution and works independent from the OS  
// Internals
chrome://predictors - omnibox predictor stats (tip: check 'Filter zero confidences')
chrome://net-internals/#sockets - current socket pool status
chrome://net-internals#dns - Chrome's in-memory DNS cache
chrome://histograms/DNS - histograms of your DNS performance
chrome://dns - startup prefetch list and subresource host cache

#enable-nostate-prefetch (default)
#enable-new-preconnect (default) 
```

```
// Firefox
network.predictor.prefetch-force-valid-for;10
network.predictor.prefetch-min-confidence;100
network.predictor.prefetch-rolling-load-count;10
network.prefetch-next;true
```

This OP didn't gave any value information or context. This is seriously nothing decentraleyes need to worry about, since this is official [W3C related](https://www.w3.org/TR/resource-hints/) in order to improve the overall latency and to handle the resources better. 

I don't see how and why decentraleyes should interference here and that's the reason I downvoted it, especially because [this was already written back in 2016](https://scotch.io/tutorials/browser-resource-hinting-with-prefetch-preconnect-and-prerender). The overall speed increases and no one likes slow website loading, and a website owner needs to use integrate the snippet into his <head> tag in order to 'enable' the function.

**Comment by Synzvato** [comment]
Hi everyone, and thanks for sharing your personal thoughts and findings.

The extension automatically disables link prefetching. This is necessary in order to prevent any disallowed requests from leaking out to delivery networks. So, I'm happy to say that users are already protected.

> This is [...] nothing decentraleyes need to worry about, [...] and no one likes slow website loading [...].

@CHEF-KOCH Feel free to uncheck _"Disable link prefetching"_ inside of the extension options screen.

**Comment by CHEF-KOCH** [comment]
Well, thanks I'm aware of it I guess the main concerns which I will cover here are:
* Referer which possible places a cookie - This can be avoided by disallowing 3rd-party cookies. This is usually when you for example google for "github", then it sends a cookie back back and forth. This is already possible to control since years in every Browser (without any extensions).
* Prefetching might causes more or redundant traffic when you won't click the link. On mobile devices with a limited data traffic this is maybe problematically, this however is anyway no problem, [double fetches](https://bugs.chromium.org/p/chromium/issues/detail?id=652228) can be avoided by using a patched Browser.  A test for this is avbl. [here](http://paulirish.github.io/web-feature-availability/).

**Comment by EC-O-DE** [comment]
Thanks for all the input Che & Syn.
What strikes the most here is that it wasn't too long ago when there was only "prefetch" --- fast forward to at least 4 different features for the browser and server to chat.
This is not an end of this evolution... Good to keep an eye on.
CHEF-KOCH thanks for posting detailed intro of those flags. Much appreciated.
