### ISSUE TITLE
Add rules for Chinese mirrors to the FAQ

### ISSUE THREAD

**Issue by crssi** [Synzvato/decentraleyes#286]
https://github.com/Synzvato/decentraleyes/releases/tag/v2.0.4 says: Implemented support for popular Chinese CDN mirrors

Should uBO /uM rules list at https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions be updated?

**Comment by ghost** [comment]
I had exactly the same interrogation when I discovered Decentraleyes 2.0.4 update, jumping then to the FAQ section here. Nothing mentioned indeed concerning the new popular Chinese CDN mirrors.

**Comment by Synzvato** [comment]
Hello, and thank you for bringing this up. I have since updated the [section in question](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on), and it should now reflect the new situation. In short, ```sdn.geekzu.org``` and ```ajax.proxy.ustclug.org``` were added.

**Comment by ghost** [comment]
OK, Hi and thanks, @Synzvato !

**Comment by crssi** [comment]
Fantastic and thank you for your great work and commitment.
I really appreciate your work.
Cheers
