### ISSUE TITLE
Security downsides?

### ISSUE THREAD

**Issue by RoxKilly** [Synzvato/decentraleyes#3]
I understand how intercepting network requests and injecting JS script instead would increase speed and enhance privacy (reduce the opportunity for tracking). A short FAQ on how this works would be really helpful, for people who are technically literate enough to understand the technology, but don't feel comfortable reading code. For instance after a bit of research, I still have the following questions:

1. One benefit of contacting the origin server, especially over `https` connections, is the guarantee that the script is authentic.  Given that this extension would not communicate with the origin server, are there safeguards in place to check the integrity of script before injecting it?  Is it possible for another application to modify the scripts in the local cache in order to get malicious script executed?

2. How does Private Browsing impact this extension?  I know that the browser clears its cache after a private browsing session, but extension settings are preserved.

3. When are the scripts downloaded? And are they saved as `.js` files on the user's hard drive?

4. Is there any mechanism to check whether a local copy is outdated? Or does the add-on assume that script at a given URL never changes?

**Comment by matthieuy** [comment]
@RoxKilly : I can't answer for all questions but :

3) Scripts aren't be download, they are include in the extension and they are save as `.js.dec`. So any cache is need to work.

4) There is any mechanism to check versioning because you request CDN for a specific version.
This extension just replace CDN files with local files.
See [resources directory of jquery](https://github.com/Synzvato/decentraleyes/tree/master/data/resources/jquery) to more understand

**Comment by Synzvato** [comment]
@RoxKilly Thanks for sharing your questions and concerns.

1. The scripts are currently all contained within the add-on and there is an audit tool included, that lets anyone verify the integrity of the local files. These checks are also performed manually by a Mozilla volunteer before a new version goes live. About file integrity, only if you have malicious code on your machine that overwrites add-on data, but at that point you'd already be compromised.

2. Private Browsing mode does not affect the behavior or effectiveness of this add-on, since the files will be fetched from disk when needed, not from your browser's cache.

3. As mentioned by @matthieuy, they will indeed be saved on the user's hard drive. Future versions will most likely have support for custom resource bundles (that will also be saved to disk).

4. This was also correctly answered by @matthieuy, thanks!

**Comment by Synzvato** [comment]
I'm closing this issue. For more details, please see [this](https://github.com/gorhill/uBlock/issues/971), previously referenced and related, issue on uBlock Origin's GitHub, kindly opened by @anewuser.

**Comment by RoxKilly** [comment]
@Synzvato Thanks for the info
