### ISSUE TITLE
Consider mirroring Google AMP

### ISSUE THREAD

**Issue by wumpus** [Synzvato/decentraleyes#49]
Google AMP is about to be released in a big way, and it would be awesome if decentraleyes supported it.

Just one file is needed: https://cdn.ampproject.org/v0.js

Thanks! I love this software, very smart idea and implementation.

**Comment by stewie** [comment]
OMG
I guess you don't realize what you're suggesting. You just heard it's the latest greatest thing, eh?

check it out:
open a browser tab and retrieve https://cdn.ampproject.org/v0.js
copy all, then open another tab to http://jsbeautifier.org and paste

you'll discover that v0.js chainloads https://3p.ampproject.net/1456440290687/f.js
which serves to further load
a boatload of other scripts from advertising domains

**Comment by stewie** [comment]
Aside from its content, is "v0.js" even stable/cacheable ?
It's being served with headers indicating it is not (not stable, not cacheable)
Last-Modified: Feb25, 2016
Expires: -now-

**Comment by wumpus** [comment]
My suspicion is that caching it now will work great into the future. Personally, I'd love to alter this js to shoot out all of the ads, but I'm not about to start claiming that perfection is the enemy of the good.

**Comment by RoxKilly** [comment]
> My suspicion is that caching it now will work great into the future.

Why do you think so?  If the script or the access URL changes, it will cause a problem because DecentralEyes needs to inject an identical script when its correct URL is parsed. As of right now, the response headers to [the script](https://cdn.ampproject.org/v0.js) include `Expires: Thu, 03 Mar 2016 06:33:33 GMT`, exactly 12hrs from when I retrieved the file.

**Comment by Synzvato** [comment]
@wumpus Thanks for your suggestion!

I must say that I'm also very hesitant to implement this, mainly since it's clearly designed to speed up websites that rely on third party trackers. There's even an optional component, [Google AMP Cache](https://www.ampproject.org/docs/get_started/about-amp.html), within the standard about siphoning all ad loads through Google "for maximum efficiency".

That, along with the fact that it's unversioned and not too popular at this point (generally, only libraries that rank high in current statistics #7 are added), means I will need to pass this up for now.

I'm very glad that you like the concept, and many thanks for contributing!

**Comment by wumpus** [comment]
You guys are a riot.

**Comment by Synzvato** [comment]
@wumpus I think these are all very valid arguments. I also think (and I only represent myself here) that I have been very decent towards you whilst explaining my views on your suggestion.

If you believe any of these statements to be untrue, please do weigh in.

**Comment by wumpus** [comment]
Well, since most of the comments make big assumptions about what I proposed, and my comment about stripping out all of the ads was basically ignored, I didn't feel that making replies would be useful because you keep on saying that I'm proposing sending people to ads and trackers, when in fact I want to strip them. If AMP launches big enough, I'll just clone this project and do my own thing. Thanks for providing an open-source base for that, but you get an F for community.

Please don't @ me again, thanks.

**Comment by stewie** [comment]
Sorry if my earlier comment put you on the defensive, wumpus. Synzvato's replies though really have been super-extra courteous across all the issues threads here.

I too want to strip them. That's uBlock extensionterritory though (or NoScript surrogates). Here, Synzvato isn't facilitating roll-yer-own locally injected scripts. I wish decentraleyes would, in fact, support that functionality.

**Comment by RoxKilly** [comment]
Didn't mean to offend. I just asked why you felt that caching would work great in the future and raised my own concerns. What big assumptions have we made? How have we "kept on" suggesting that you're trying to send people to ads? I don't understand.
