### ISSUE TITLE
Twitch login does not work with Decentraleyes

### ISSUE THREAD

**Issue by 4DEATH** [Synzvato/decentraleyes#51]
I just had a problem with it. Twitch login prompt is invisible with Decentraleyes active.

twitch.tv
Firefox 45.0
Decentraleyes 1.2.2

**Comment by Synzvato** [comment]
@4DEATH Thanks for reporting the issue! It's a known problem and I'm happy to say that a fix for this will be pushed out with the very next release (see issue #22).

For now, you can fix this by adding ```passport.twitch.tv``` to your whitelist *(Add-on Manager Preferences)* or by logging in from https://twitch.tv/login instead of using the login pop-up.
