### ISSUE TITLE
Put this add-on at the top of the request interception list

### ISSUE THREAD

**Issue by gsurrel** [Synzvato/decentraleyes#53]
(Sorry for the issue title, I couldn't find a better one)

I am currently browsing by blocking by default all third parties thanks to [uBlock Origin](https://github.com/gorhill/uBlock), both for browsing speed and privacy. And blocking ads, too.

The problem is that uBlock blocks the requests before Decentraleyes can provide the local version. Is it possible to set Decentraleyes at the very beginning of the chain of plugins working on the requests made by the browser?

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by Synzvato** [comment]
Thanks for sharing your concerns and ideas!

Putting Decentraleyes at the top of the list is impossible, because Mozilla does not allow add-on creators to alter the order in any way. This makes sense, because multiple add-on creators would probably want their add-on to be at the top of this list and that would result in the very same issue.

Here are two options for working around your problem:

1. Put uBlock Origin in ```Advanced Mode``` if you haven't done so already, and allow [known CDN domains](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on) on a per-page basis if you see that things break.
2. Whitelist all [known CDN domains](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on) in uBlock Origin's settings panel and manage whitelists and further settings for these domains through Decentraleyes' Add-on Preferences dialog.

I think the first option would be more in line with your current approach. About the title, no worries. I've shortened it a bit to keep it on one line. I hope this helps, but feel free to let me know if it doesn't.

**Comment by gsurrel** [comment]
Thanks for the answer. I've whitelisted all Decentraleyes' domains, it's the easiest on the long-term.

**Comment by Synzvato** [comment]
My pleasure, I'm happy to hear this solved your issue.
