### ISSUE TITLE
Will you support Optimizely and similar CDNs?

### ISSUE THREAD

**Issue by malimM** [Synzvato/decentraleyes#55]
This is a very interesting project for which I thank the developer for bringing to us. 
I read the FAQ and it says: "This will all block traffic to supported CDNs" with regards to uMatrix, does this mean Decentraleyes only supports CDNs limited to a predetermined list? 
I've seen for example many sites contents being delivered by 'Optimizely', does this mean Decentraleyes isn't prefetching any content from the CDN 'Optimizely' since it doesn't ask for it to be on the uMatrix rule set?
[For example](https://www.microsoft.com/en-us/store/games/killer-instinct/9nblggh1z149) Microsoft uses 'Optimizely', is Decentraleyes fetching its resources if it's whitelisted in uMatrix? My question overall is can we add 'Optimizely' to the list? Since it's being used by a fairly large amount of sites?

**Comment by Synzvato** [comment]
My pleasure, I'm glad you like it. Thanks for sharing your thoughts!

> I read the FAQ and it says: "This will all block traffic to supported CDNs" with regards to uMatrix, does this mean Decentraleyes only supports CDNs limited to a predetermined list?

Yes, it supports all popular JavaScript Content Delivery Networks for websites as analyzed and [reported](http://w3techs.com/technologies/overview/content_delivery/all) by W3Techs, because chance of occurrence is by far the most important factor involved.

> For example [...], is Decentraleyes fetching its resources if it's whitelisted in uMatrix? My question overall is can we add 'Optimizely' [...]? Since it's being used by a fairly large amount of sites?

The domain ```cdn.optimizely.com``` does not hold popular JavaScript libraries. Optimizely is a tracker (an analytics service) and its CDN is meant to serve you its tracking scripts. Decentraleyes only injects vital resources such as jQuery (to keep websites from breaking).

Simply blocking Optimizely using uMatrix should not cause you any issues.
