### ISSUE TITLE
Load all resources from CDN if any are missing

### ISSUE THREAD

**Issue by elypter** [Synzvato/decentraleyes#56]
from https://www.reddit.com/r/privacy/comments/4cfw4k/firefox_addon_decentraleyes_replaces_3rd_party_js/d1igkhf

It could be a good idea that Decentraleyes didn't bother replacing an asset coming from a given domain if another request is going to be made to this domain anyway. Well, for the privacy side of things at least. There's also the speed factor. It could be an option.

**Comment by RoxKilly** [comment]
@elypter Interesting. It's true that if one asset is fetched from a CDN (eg: font from Google), while the other asset is served locally (eg: Google JS library) the user's privacy is not as well protected as if everything was served locally.  On the other hand I don't think that fetching some assets remotely while serving others locally significantly increases fingerprinting accuracy.  True, the CDN server will know that Javascript is blocked but the server already knows that unless you block all CDN connections and serve images, stylesheets etc... locally.

In my opinion, it is better to serve JS locally whenever possible because the user still gets to benefit from reduced bandwidth usage, and faster loading - 2 of the best benefits of this addon.

**Comment by elypter** [comment]
if scripts are elaborate enough they should be able to detect and report that the second script is running although it has not been loaded. this can only happen if you have this addon installed. the pattern of what is blocked and what not is not a proof that this addon is used but a strong indicator and certainty can be improved by multiple site access. fingerprinting can be very sneaky and although i dont think commercial trackers look at every detail software is adapting and will probably look for patterns automatically one day.

it should not be the standard since for most users the page load speed is more important but it would be nice to have it as an option for security concerned people.

**Comment by Synzvato** [comment]
Hi, @elypter and @RoxKilly, and thanks for sharing your thoughts on this! The ```GUI``` introduced in ```v2.0.0``` makes it much easier to completely whitelist a given website. What this means is that you can achieve exactly what you want, by following the instructions below. Feedback is highly welcome.

1. Follow [this guide](https://github.com/Synzvato/decentraleyes/wiki/Frequently-Asked-Questions#why-doesnt-it-deliver-resources-from-cdns-i-block-using-a-different-add-on) to ensure delegation of supported CDN-requests to Decentraleyes.
2. Use the domain whitelist button in case you need any missing resources.

![image](https://user-images.githubusercontent.com/2366020/33095889-eb1c41d4-cee3-11e7-8012-1370088c9dac.png)
_The domain whitelist button is located inside of the extension popup._
