### ISSUE TITLE
Add jQuery CDN mappings for two-sequence identifiers

### ISSUE THREAD

**Issue by Gitoffthelawn** [Synzvato/decentraleyes#63]
Handle jquery from code.jquery.com in all cases.

Example of popular site where it's not working: https://notepad-plus-plus.org/

**Comment by Synzvato** [comment]
The website uses shorthand notations. These types of constructions have been deprecated by pretty much all known CDNs. It's considered to be a bad practice to not specify exact versions.

Having said that, it's great that you've spotted these shorthands. Since CDNs still support them for legacy reasons, Decentraleyes should, too. Let's support them, and label all shorthands ```Deprecated```.

**Comment by Gitoffthelawn** [comment]
Thanks!

For documentation purposes, can you provide an example of shorthand vs. non-shorthand?
