### ISSUE TITLE
Provide the ability to create file mappings

### ISSUE THREAD

**Issue by stewie** [Synzvato/decentraleyes#75]
Many of the assets I would hope to replace do not appear in any "commonly used libraries" list, so I'm asking your to please consider supporting custom mappings. This could be a gui-less advanced feature. At startup, decentraleyes would just parse an additional custom_mappings.txt file, loading custom pairs of regex url match rule + file://path/to/replacement

**Comment by Synzvato** [comment]
Thanks for sharing your thoughts! We would need to check if this is possible. Once this add-on is ported to ```WebExtensions```, all bundled resources will need to be marked as "web accessible resources" within the add-on's manifest file. Forwarding requests to arbitrary system files might not be doable.

**Comment by dannycolin** [comment]
Eh @Synzvato I think it would be great to support custom resources. So, I just gave a look at the source code and it seems the resources are hard coded in the plugin especially in the core folders (files.js, mapping.js, resources.js). 

So I was thinking, instead of that we could create a file for each resources. That way everyone can add their one url-rules files without modifying a core file. Even better, we could have an interface for the addon where people can add or delete url-rules and the resources files that are linked to it. It would be a bit like the userstyle addon where you can download custom style but instead we would be able to download custom url-rules and resources.

I don't know if it makes sense. If not let me know and I'll try to explain it with more details. Anyways, Let me know what you think about the idea.

**Comment by Synzvato** [comment]
Hi @dannycolin, and thank you for weighing in. I do think I understand what you mean. The idea, of allowing end-users to create custom mapping rules for existing libraries, is definitely interesting. However, encouraging said users to subscribe to third-party resource repositories, can be pretty dangerous.

Please see issue #6, as it seems to be directly related to your ideas. Feel free to share any thoughts.
