### ISSUE TITLE
Why doesn't this add-on serve all resources locally?

### ISSUE THREAD

**Issue by grenzor** [Synzvato/decentraleyes#81]
Hi, firstly thanks for the great addon, I'm looking forward to using it more! I'm a little new to using it so forgive me if I'm incorrectly doing something wrong. 

I installed the addon (on latest Firefox version) and went to the addon's test site which said I had configured it correctly. I can also see the counter going up when testing it there but when I visit a random site with libraries it still requests it e.g. https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js. Visting another version the library loads it locally - https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js (btw from what I can see using the ublock logger even if it is loaded locally, a document request is sent to the server but using ff's internal network requests there is no request made - which is right?). 

Going back to the main point, do you know why some requests aren't loaded locally..I'm assuming local libraries cannot work with older library version? Also not getting seeing any comments saying locally hosted libraries are being used?

**Comment by Synzvato** [comment]
@grenzor My pleasure, I'm very happy you like it, and thanks for getting in touch! It's true that version 1.12.2 of jQuery does not come bundled with Decentraleyes. The selection of included files currently depends on statistics by W3Techs, as explained further in issue #7 and discussed in #83.

In short, it's a trade-off between the size of the add-on, and its overall effectiveness. So whilst the add-on does not provide complete coverage, it does contain all reasonably common library versions.

> From what I can see using [...] there is no request made - which is right?

Yes exactly. Seeing no request for the resource in question in the network panel clearly indicates that said CDN-request was intercepted and processed locally by Decentraleyes.

> Also not getting seeing any comments saying locally hosted libraries are being used?

These comments should appear inside the script files in the developer tool ```Debugger```. If they do not appear, please take a close look at Decentraleyes' add-on preferences.

**Comment by PeterDaveHello** [comment]
It's hard to host them all locally, take cdnjs as example, the extracted files take 34 GB, even the compressed git repository takes 1.8GB, maybe could add a feature that still download everything from CDNs to client every time, but save them in a special space to keep them locally forever, so only the first request leaks user info, then never! @Synzvato what do you think?

**Comment by golfingpanda** [comment]
Please consider providing an option to allow the user to host them.. on amazon s3, but better cloud agnostically.

**Comment by TriMoon** [comment]
> @PeterDaveHello + @Synzvato https://github.com/Synzvato/decentraleyes/issues/81#issuecomment-219230475
> ... maybe could add a feature that still download everything from CDNs to client every time, but save them in a special space to keep them locally forever, so only the first request leaks user info, then never!

Why not have a user configurable setting to auto-prune locally cached files after a certain unused time? fe.

1. If some resource is not locally deliverable download and store it locally.
1. If a resource is delivered locally, update the last used time of that resource in a locally tracking property for that resource.
1. From time to time (user settable), check the last used time from the locally tracking property for all resources.
  1. If time exceeds; prune that resource to free local space.
  1. Ofcourse make sure these also get properly cleaned when the extension is uninstalled :wink:

**Comment by PeterDaveHello** [comment]
> Why not have a user configurable setting to auto-prune locally cached files after a certain unused time? 

It'll be good to have that option, but for privacy reason, I may try to keep them forever, maybe to have a local cdnjs or jsdelivr is also an option for user?

**Comment by Gitoffthelawn** [comment]
I might be oversimplifying things, but for desktop and laptop computers, which nowadays have non-volatile storage ranging from 500GB to 8TB, keeping even 1-2GB of locally available libraries seems like it would not pose a significant impact on free storage availability.  (Obviously, this is not the case for tablets and smartphones.)

I would like to see Decentralyze include even fewer (or zero) libraries, and gain the ability to download and store locally *every* library used by a significant number of sites.

I'd even like it to redirect requests for jquery and similar libraries made by common sites that are *not* requested from a CDN in order to reduce data usage and increase website loading speed.

**Comment by Synzvato** [comment]
@PeterDaveHello

> It's hard to host them all locally, take cdnjs as example, the extracted files take 34 GB, even the compressed git repository takes 1.8GB [...]

It is hard indeed to host all files locally. Especially in the case of cdnjs which has a very large library catalog. That's why Decentraleyes relies on web crawling statistics to figure out what libraries have a significant amount of web presence. Quite a few resources are hardly ever used on websites.

> [...] could add a feature that still download everything from CDNs to client every first time, [...] to keep them locally forever, so only the first request leaks user info, then never!

In addition to bundling a fixed collection of most popular libraries and versions, I'm all for a better caching solution that can be used in the event that Decentraleyes is forced to contact a CDN.

@TriMoon

> Why not have a user configurable setting to auto-prune locally cached files after a certain unused time? [...] This would make #7 automated without needing to update things.

Yes, I think that (optional) auto-pruning is essential in combination with a custom caching mechanism. The bundle mentioned in #7 would remain a separate aspect. In fact, the default bundle is quite easy to maintain as it turns out that library usage trends change surprisingly gradually.

@Gitoffthelawn

> I might be oversimplifying things, but for desktop and laptop computers, which nowadays have non-volatile storage ranging from 500GB to 8TB, keeping even 1-2GB of locally available libraries seems like it would not pose a significant impact on free storage availability.

In my experience people are going to fall over an add-on that takes up 1-2 GB of local disc space, especially when they install core applications like browsers on their SSDs.

> I would like to see Decentralyze include even fewer (or zero) libraries, and gain the ability to download and store locally every library used by a significant number of sites.

This would take away the main philosophy behind Decentraleyes. Namely the fact that it aims to make people rely less on Content Delivery Networks. It already knows what libraries are used by a significant number of sites thanks to web crawling statistics. That's why it's able to inject this many local files.

Of course, a better caching system for unavailable resources would be great, but I don't think that _not_ including commonly used libraries is a good idea as it makes you more dependent on CDNs.

**Comment by fastcopy** [comment]
http://ajax.googleapis.com/ajax/libs/jquery/1.*/jquery.min.js
---> decentraleyes serve latest 1.x file

http://ajax.googleapis.com/ajax/libs/jquery/2.*/jquery.min.js
---> decentraleyes serve latest 2.x file

I think you don't have to include all of them because some of them(e.g., 1.9.x ~= 1.9.y) are almost same file.
Just use * to catch all of them.

**Comment by fastcopy** [comment]
Also, you can "mimify" the javascript code which included in this add-on.

+ remove comments and version info.
+ remove lRlN to make it minimal. e.g., http://jscompress.com/

**Comment by ArchangeGabriel** [comment]
Is there a better issue replacing this one? I’d like to see Decentraleyes start with zero (or just a few) libs and download other on first use, with eventually a pruning of old, unused library (e.g. wasn’t requested by any website for 6 months). Because currently I visit far too much website still getting their resources from Google CDN, because for instance `https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js` is not provided.

**Comment by Synzvato** [comment]
> [...] currently I visit far too much website still getting their resources from Google CDN, because for instance https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js is not provided.

@ArchangeGabriel I'm glad you have decided to bring this up. The reason that the example does not result in a local injection, is an absent shorthand notation, not a missing library. Based on your findings, I have added support for this type of reference. You will find the [new shorthands](https://github.com/Synzvato/decentraleyes/commit/08f9a489b8c2d7bd8f221befbbaaf2abf0492a5e#diff-af2dd5d506fa585c254d2cb7721c7372R24) in the next release.

> [...] it seems like it could work [...] have you considered or tested out whether serving the latest library version of 1.x allows sites that serve older 1.x libraries to function properly?

@grenzor We are definitely not the first project to consider taking this route. Interestingly, a while ago, Google Hosted Libraries allowed you to request e.g. version ```1```, or version ```1.8``` of jQuery, which would dynamically point you to the latest minor or patch version. This caused issues, and was deprecated.

The same thing can be said about most other networks. I don't think this is a good way of saving space.

**Comment by ArchangeGabriel** [comment]
@Synzvato Ah, OK, thx. :)
