### ISSUE TITLE
Change the behavior of the release notes system

### ISSUE THREAD

**Issue by najjara** [Synzvato/decentraleyes#84]
Since this is a restartless addon, it'll update on the fly while browsing.

But unlike traditional addons, making the release notes appear after updating can be problematic. In a traditional addon, if a page is forced to load (such as a changelog) it's not a problem, because the browser is empty and the user isn't yet engaged in browsing.

But it's distracting to have the tab that I was on suddenly be switched to a new one unannounced. I still want to see the notes (so I don't want to disable them), but maybe the loaded tab shouldn't be focused immediately. Or maybe give a floating window that says it has been updated.

**Comment by Gitoffthelawn** [comment]
That's a good point.  Maybe Thomas can switch it to a background tab or have an option to disable it.

Note that the *changelog* is completely local in this extension, which is wonderful.  So many extensions load an external URL for the *changelog*... but not this one!  The hypocrisy would be notable if it loaded an external resource for a *changelog*.  Many thanks to Thomas for making it a local resource.

**Comment by B00ze64** [comment]
Good day.

> But unlike traditional addons, making the release notes appear after updating can be problematic. In a traditional addon, if a page is forced to load (such as a changelog) it's not a problem, because the browser is empty and the user isn't yet engaged in browsing.

You are assuming that everyone loads their browser "empty" - mine starts off with ~200 tabs loaded, and 1 extra tab is not a surprise for me. But I agree, loading the tab in the background is a good idea.

**Comment by ciechiw** [comment]
Alternatively, and this is my preference, it would be nice if the release notes tab gets opened at the next browser start, like happens with Firebug, for example. I've never seen an addon other than decentraleyes that opens a release notes tab while browsing, and it's very distracting.

**Comment by Gitoffthelawn** [comment]
@ciechiw After hundreds of thumbs ups, I think that's my first thumbs down!  LOL.  Nothing personal, I assure you.  Actually, your point and observation are both well-taken.  Furthermore, I agree with you that a release notes tab appearing while browsing is not ideal.  But honestly, I would be more bothered by a release notes tab that opened at the start of the next session.  Nothing worse than opening the browser planning to do something and being presented with release notes for an extension.  Okay, there are much worse things.

But seriously, I think a simple toggle to show/hide release notes would be a fair compromise.  Or, if it's a big issue, a dropdown with three options:
  1. Show release notes as background tabs
  2. Show release notes as foreground tabs
  3. Do not show release notes

**Comment by ciechiw** [comment]
@Gitoffthelawn 
being the good Samaritan I am, I'll help you with the following instructions, despite your public shaming of me ...

1) enter "about:config" in the location bar
2) enter "extensions.jid1-BoFifL9Vbdl2zQ@jetpack.showReleaseNotes"
3) toggle the key to false

this bug is for users who do not wish to disable the release notes, but prefer that they are not as intrusive.

**Comment by Gitoffthelawn** [comment]
@ciechiw Sarcasm is hard to convey in writing, so if you are being sarcastic, LOL.  If you aren't being sarcastic and feel that I publicly shamed you, you have my sincere and humble apology.  I definitely didn't want to express that.

I like the current release notes mechanism.  I prefer it over the idea of having release notes show up on the next launch, and was proposing a solution that could accommodate everyone.

Since releases aren't that common, and thus release notes are infrequent, I would actually prefer Thomas spend his time on bigger issues.

**Comment by Synzvato** [comment]
Hi everyone, and many thanks for sharing your personal thoughts!

> But it's distracting to have the tab that I was on suddenly be switched to a new one [...]. I still want to see the notes [...], but maybe the loaded tab shouldn't be focused immediately.

@najjara I have taken another look at the feature. As a result, ```v2.0.0``` opens up release notes, without bringing focus to corresponding tabs. This is in line with your request, and most related feedback.
