### ISSUE TITLE
Why do I see DNS queries for blocked domains?

### ISSUE THREAD

**Issue by ghost** [Synzvato/decentraleyes#98]
.

**Comment by Synzvato** [comment]
@z9Z6tG5i2 What connection, under what circumstances, using which settings? What exactly makes this a big privacy issue? Some additional, specific, information would be highly appreciated.

**Comment by z9Z6tG5i2** [comment]
You can test it using a packet analyzer like Wireshark, if you select the option to not load third party content if local isn't available, or even if you don't select that option but the content were already downloaded, you can see the dns queries are still sent to the cdn provider but the connection to the IP address received from the dns query is blocked. It's a big privacy issue because the propose of the addon is to block connection to those shit companies, but if the dns queries are still sent they can see our IP anyway and if they analyze they might even see we are using an addon to block them.

**Comment by Synzvato** [comment]
@z9Z6tG5i2 I did in fact analyze the traffic and nothing of the sort showed up on my end. Could you please send me your traffic analysis results? That could shed some light on the issue.

**Comment by z9Z6tG5i2** [comment]
For example this website uses cloudflare and as you can see the dns queries are not blocked:

![dns](https://cloud.githubusercontent.com/assets/19496756/15450743/ec4abdac-1f93-11e6-8909-f0b785019bb6.png)

**Comment by Gitoffthelawn** [comment]
This is turning into a good discussion.  I don't want to throw it off topic, but I do have a quick question for @z9Z6tG5i2 : You referred to CDN's as *"shit companies"*.  I'm interested in knowing why you view the CDN's as *"shit companies"* and not the companies/sites that chose to use them as the problem?  Aren't the sites that choose to use them the real problem?

**Comment by Synzvato** [comment]
@z9Z6tG5i2 I must say that I'm getting entirely different results and see no DNS queries for CloudFlare when blocking requests for missing resources. But even if these requests are sent out in specific cases (e.g. on certain platforms), I still don't understand how this is a big privacy issue.

I say this because DNS queries are not sent to the host you're trying to reach (CloudFlare in your case), but to a name resolution service. Also, routers tend to be quite good at caching DNS records, so hardly any of these requests should ever leave your local network. Am I missing something?

**Comment by z9Z6tG5i2** [comment]
@Gitoffthelawn If you were a Tor user you would start getting some hate on certain cdn providers.

@Synzvato Weird, did you tried on different platforms? It might block well on windows but not on linux, that's what i'm using. And yes, it might not be a -big- privacy issue but leak is still a leak. Don't forget dns servers have logs too, for some reason google is running one.

**Comment by Synzvato** [comment]
@z9Z6tG5i2 I use Linux too, so that can't be the problem. Before we continue discussing, have you tried navigating to ```about:config``` and setting the preference ```network.dns.disablePrefetch``` to ```true```?

**Comment by Gitoffthelawn** [comment]
@Synzvato I was wondering the same thing.  Although it would be neat if this extension could handle DNS prefetching.

@z9Z6tG5i2 Why do Tor users hate on certain CDN providers?

**Comment by Gitoffthelawn** [comment]
Relevant: This just popped up in the AFWall+ git repo: https://github.com/ukanth/afwall/issues/528

**Comment by z9Z6tG5i2** [comment]
@Synzvato yes I use that setting.
@Gitoffthelawn because every site that uses cloudflare asks for a captcha if the user is using Tor.

**Comment by z9Z6tG5i2** [comment]
@Synzvato Ok I found the culprit! It's the addon NoScript. Not sure why though.

Btw, some sites like the one I tested use custom domains with cdns, that way Decentraleyes has no effect because it doesn't know the domain is using a cdn. Would be possible to detect those domains as cdns? For example, with a built-in list of known ip addresses or by query the authority section of the domain? Another idea would be adding a field on the settings page so we can add those domains manually.

**Comment by z9Z6tG5i2** [comment]
@Gitoffthelawn because most sites that use cloudflare ask for a captcha if the user is using Tor.

**Comment by z9Z6tG5i2** [comment]
I noticed you changed the label to question but I think this is a bug because it's clear Decentraleyes conflicts with NoScript and it's not NoScript fault. I'm not a programmer but I kinda understand what's happening. For example, if you whitelist cloudflare on NoScript and the resources are available locally (or third party requests blocked) it will query the domain anyway. I guess that's because Decentraleyes doesn't have sufficient "authority" over NoScript or the method used for blocking requests isn't very reliable, or some other bug. Other addons block well with NoScript whitelist. And this affects a large scale of users considering many Decentraleyes users probably use NoScript too. If you don't mind I changed the title to a proper one.

**Comment by Synzvato** [comment]
@z9Z6tG5i2 

> I think this is a bug because [...] Decentraleyes conflicts with NoScript and it's not NoScript fault.

Please provide some specific details instead of speculating on the matter. I'm very open to actual bugs, especially those that affect user privacy, but I just can't wrap my head around your explanation.

How would this a DNS query for ```cdnjs.cloudflare.com``` be any more revealing than the DNS query for the _actual_ address you're visiting? Why this is a problem is beyond me. I know you initially stated:

> It's a big privacy issue because the propose of the addon is to block connection to those shit companies, but if the dns queries are still sent they can see our IP anyway and if they analyze they might even see we are using an addon to block them.

The CDN cannot see your IP address and your preferred DNS service (note that you can host your own) already knows what domain you're visiting. So what exactly are your concerns?

**Comment by z9Z6tG5i2** [comment]
I think you are giving too much attention if it is a big privacy issue or not rather than the bug itself. I don't have any concerns, but you asked me why it is a big privacy issue and I just explained. A dns leak might not be a big issue for us, but for someone in some oppressive country or for a variety of reasons it might be. The "shit companies" part is just my opinion though.

But the point of all this is that the addon should block everything (dns and ip) regarding the addons the user has installed, and that's not what's happening. I already provided you all the details you need to reproduce the bug, it's not speculation. Just install NoScript, whitelist a domain and you can see for yourself. I just can't point you the lines of the code that are causing this because I'm not a programmer (if I was I was very glad to help with a pull request), but as a user I can analyze how the browser is behaving.

Cheers

**Comment by LimboSlam** [comment]
@z9Z6tG5i2, give examples that can be tested is what I think @Synzvato wants from you. I also don't think Decentraleyes is meant to block anything, but to supplement the certain content with something cleaner.

**Comment by z9Z6tG5i2** [comment]
I already gave examples to be tested:

> For example, if you whitelist cloudflare on NoScript and the resources are available locally (or third party requests blocked) it will query the domain anyway. I guess that's because Decentraleyes doesn't have sufficient "authority" over NoScript or the method used for blocking requests isn't very reliable, or some other bug.

> Just install NoScript, whitelist a domain and you can see for yourself.

@LimboSlam I also think that way, but bug is a bug I'm just reporting it. I guess the confusion in this issue is that there are too many facts mixed with opinions. :-)

**Comment by RoxKilly** [comment]
@z9Z6tG5i2 , if you disable DecentralEyes, do the DNS queries occur when the CDN is whitelisted in Noscript?  What about when the CDN is blocked?

**Comment by z9Z6tG5i2** [comment]
@RoxKilly Yes they occur in both ways, whitelisted or blacklisted. I even went further and tried all non-default settings of NoScript on about:config but the leaks persist. I also tested with the addon Request Policy by blacklisting the cdn and whitelisting on NoScript and it blocks properly, it was this kind of "authority" I was talking. If I use both addons with Decentraleyes, the protection from Request Policy is lost because Decentraleyes makes the browser query the dns.

**Comment by Synzvato** [comment]
@z9Z6tG5i2

> I also think that way, but bug is a bug I'm just reporting it. I guess the confusion in this issue is that there are too many facts mixed with opinions. :-)

I don't think that's the problem here. In my opinion, this simply doesn't qualify as a bug, since a bug typically disrupts an application requirement or a promised feature. Decentraleyes is meant to keep a large amount of websites from breaking when blocking requests for major delivery networks.

Nowhere does it state that it prevents traffic to your DNS provider. As far as I can tell, there are no downsides to this. If anything, the fact that these name resolution requests are sent on certain setups, and not on others, improves your privacy by distorting potential fingerprints.

It's great that you decided to report this, as this surely is interesting behavior, it's just not a bug. As a quick related tip, if you are concerned about your current DNS provider, then you might want to look into ```Dnsmasq``` for local DNS caching. It runs on routers with ```DD-WRT``` (or similar firmware).

**Comment by RoxKilly** [comment]
@z9Z6tG5i2  If the DNS queries occur with DecentralEyes disabled, I'm not sure why you're blaming this add-on. Why isn't it a NoScript issue?

**Comment by z9Z6tG5i2** [comment]
@Synzvato Bug might not be the proper word but I considered it as bug because it conflicts with another addon, and the faq says it is designed to work well with other addons including NoScript so it's kind of a feature, but you're the creator you know these things better.

@RoxKilly Yes but that's different, NoScript behaves that way but that's when other addons take place.

I wish I had programming knowledge to explain better my view, but Request Policy for example blocks IP and DNS regarding what is whitelisted on NoScript. You could get some ideas from the code of Request Policy and see how it is blocking the requests. Maybe this is because Firefox checks NoScript rules first then Decentraleyes.

Also thanks for the tip.

**Comment by Gitoffthelawn** [comment]
@z9Z6tG5i2 The word you are seeking is ***conflict***.  There appears to be a conflict between this extension and NoScript in that there is an unintended side effect.  The conflict is not so serious as to prevent the extensions from being used together, but is serious enough to create the issue you helpfully identified.

**Comment by Synzvato** [comment]
@z9Z6tG5i2

> I wish I had programming knowledge to explain better my view, but Request Policy for example blocks IP and DNS regarding what is whitelisted on NoScript.

Isn't the difference here simply that RequestPolicy cancels the request where Decentraleyes redirects it to a local resource? This is comparing the results of two distinct types of actions.

@Gitoffthelawn

> The word you are seeking is conflict. There appears to be a conflict between this extension and NoScript in that there is an unintended side effect.

I'm not even sure if you can call this a conflict. As far as I know, none of these three add-ons make any specific promises on DNS traffic. In essence, the absence of these specific DNS requests is a side-effect of blocking all traffic to the third parties in question. Does this alter documented behavior?

**Comment by Gitoffthelawn** [comment]
@Synzvato I think it's borderline to call it a conflict.  But given that one of your users has notified you that it's not working as expected, and the reason is because of running another extension, I think it's okay to make that call.

Another term could be ***side-effect***, but to be honest, I think it's a little more than a side-effect, and a little less than a conflict.  Maybe it's a ***side-conflict***, but I think that's what happens when you eat doughnuts and fried spicy wings at the same time.  :-)

**Comment by Synzvato** [comment]
@Gitoffthelawn

> But given that one of your users has notified you that it's not working as expected, and the reason is because of running another extension, I think it's okay to make that call.

Expectations are personal though. I think what matters is whether or not this add-on alters documented behavior of other installed extensions (or itself). As far as I can tell, this is not the case.

> I think it's a little more than a side-effect, and a little less than a conflict. Maybe it's a side-conflict, I think that's what happens when you eat doughnuts and fried spicy wings at the same time. :-)

Haha, I think you might be onto something there, since I haven't encountered any side-conflicts since the day on which I decided to kick meat out of my diet. :stuck_out_tongue_winking_eye: Well, up until spotting this issue, that is.

**Comment by Gitoffthelawn** [comment]
>  Expectations are personal though. I think what matters is whether or not this add-on alters documented behavior of other installed extensions (or itself). As far as I can tell, this is not the case.

As a UI/UX expert, I tend to focus more on user expectations than documented functionality.  Documented functionality can sometimes be based on poor specifications.  User expectations, except when irrational, always form a logical *tautology*: they are user expectations.

In this specific case, I see the OP's concern.  It got convoluted because they presented colloquial opinion with their report, but I think you finally got to the core.

Your statement "The CDN cannot see your IP address and your preferred DNS service (note that you can host your own) already knows what domain you're visiting. So what exactly are your additional concerns?" is a strong argument and is largely accurate (there are possible exceptions, but it gets into edge cases).

My response is that if you can snap your fingers or invest a small amount of time to accommodate this issue, go for it.  It probably won't hurt, and may help a little.  At the least, adding a FAQ note makes sense given that other users may encounter this issue.

On the other hand, if it involves a large time commitment or painful brain contortions, it may not be the best use of your time and energy.  If your brain explodes, it gets messy for everyone in the room.  And your cat will be forever traumatized.

> Haha, I think you might be onto something there, since I haven't encountered any side-conflicts since the day on which I decided to kick meat out of my diet. :stuck_out_tongue_winking_eye: Well, up until spotting this issue, that is.

That's probably why you look so healthy.  I recently read a report that the best way to "save the planet" is for everyone to become a vegetarian.  Some experts predict than in 50 years it will be unfathomable that so many people once ate so much meat.

**Comment by z9Z6tG5i2** [comment]
Well, I think I already did my job in reporting this unexpected side-conflict-something-else-effect :sweat_smile:
Hoping you can find a solution for it when you have time. If you need more details or tests it'll be a pleasure to help.

Cheers
